### ISSUE TITLE
Add an example for dynamic fields

### ISSUE THREAD

**Issue by Reprevise** [GiancarloCode/form_bloc#10]
Right now I have a system where users can click a button and it adds a new field into the `fieldBlocs` list and to a separate map in the same file. I was wondering if you could make an official example of how dynamic fields should be implemented since my system is a little janky.

**Comment by GiancarloCode** [comment]
@Reprevise At the moment there is no adequate way to add fields dynamically, in a few days I will add this functionality and add an example, although apparently it may have some breaking changes,
If you want to give a suggestion you can give them [here](https://github.com/GiancarloCode/form_bloc/issues/11).

**Comment by GiancarloCode** [comment]
@Reprevise 

🔥 form_bloc v0.10.0 support dynamic fields 🔥

Example:
[BLoC](https://github.com/GiancarloCode/form_bloc/blob/master/packages/flutter_form_bloc/example/lib/forms/dynamic_fields_form_bloc.dart) - [UI](https://github.com/GiancarloCode/form_bloc/blob/master/packages/flutter_form_bloc/example/lib/forms/dynamic_fields_form.dart)

**Comment by GiancarloCode** [comment]
@Reprevise Any suggestion is welcome 😀

**Comment by Reprevise** [comment]
Looks good, I was a bit confused about the path system at first but I think I got the hang of it. Another confusing aspect is the groups vs lists which I was confused about and caused some errors when i migrated.

**Comment by GiancarloCode** [comment]
I added this definition in the [docs](https://pub.dev/documentation/form_bloc/latest/form_bloc/FormBloc/addFieldBloc.html) of each event that use a `path`.

The `path` is a `String` that allows easy access to a `FieldBloc`s that is found in `FormBlocState.fieldBlocs`.
To access nested `FieldBloc`s, you must use the `/` character.
Examples:
* `group1/name`
* `group1/group2/name`

To access to element by the index of a `FieldBlocList` you must write the index between brackets.

Examples:
* `list1/[0]`
* `group1/list1/[5]`


If you have doubts or believe that documentation can be improved just tell me.
___
The `FieldBlocList` is usually used for add/remove dynamic fields, in simple cases you add a `SingleFieldBloc` like `TexFieldBloc` or `BooleanFieldBloc`, but for complex cases you want to add a group of this fields, in this cases is when you need to use a `GroupFieldBloc`. 
In the example I want to add or remove dynamically a group of fields that represent a member of a club.

**Comment by GiancarloCode** [comment]
@Reprevise It would be great if you could give your opinion on any of the following issues  😁
https://github.com/GiancarloCode/form_bloc/issues?q=is%3Aopen+is%3Aissue+label%3A%22feedback+wanted%22
