### ISSUE TITLE
How to use this package with editing a model (Edit page)?

### ISSUE THREAD

**Issue by egenita** [GiancarloCode/form_bloc#106]
Hi,
I am having difficulty on how to pass a parameter to the bloc from page/form.
Let's say I go to List page > Details page > Edit page, I cannot find a way to pass the model ID so that I can use this to fetch its details from API.

Can someone have already done this?
Thanks.

**Comment by egenita** [comment]
Never mind, I managed to solved it.
By the way, thanks for the great package! :)

**Comment by GiancarloCode** [comment]
The best way is to pass it through the constructor :)

**Comment by mghase** [comment]
> Never mind, I managed to solved it. By the way, thanks for the great package! :)

How did you solve it. Please share if you dont mind
