### ISSUE TITLE
Help with BooleanFieldBloc and SelectFieldBloc

### ISSUE THREAD

**Issue by jatin-rajput** [GiancarloCode/form_bloc#12]
// addFieldBloc(
    //     fieldBloc: BooleanFieldBloc(
    //         name: 'boolean',
    //  validators: FieldBlocValidators.requiredBooleanFieldBloc));

and help me to make a dropdownbloc i am new in flutter

**Comment by GiancarloCode** [comment]
Hello @jatin-rajput

`validators` is a `List<Validator>`, thanks to this you can add different validators:
```dart
  addFieldBloc(
      fieldBloc: BooleanFieldBloc(
        name: 'boolean',
        validators: [
          FieldBlocValidators.requiredBooleanFieldBloc,
          // You can add more validators...
        ],
      ),
    );
```

* A `DropdownFieldBlocBuilder` is widget that need a `SelectFieldBloc`'.
Checkout this example:
[BLoC](https://github.com/GiancarloCode/form_bloc/blob/e2b7e8f320f274b789cf032778310fd0ca01a7e1/packages/flutter_form_bloc/example/lib/forms/form_fields_example_form_bloc.dart#L21-L26) - [Widget](https://github.com/GiancarloCode/form_bloc/blob/e2b7e8f320f274b789cf032778310fd0ca01a7e1/packages/flutter_form_bloc/example/lib/forms/form_fields_example_form.dart#L51-L58)

* A `DropdownFieldBlocBuilder` with enum values example:
[BLoC](https://github.com/GiancarloCode/form_bloc/blob/e2b7e8f320f274b789cf032778310fd0ca01a7e1/packages/flutter_form_bloc/example/lib/forms/complex_login_form_bloc.dart#L28-L33) - [Widget](https://github.com/GiancarloCode/form_bloc/blob/e2b7e8f320f274b789cf032778310fd0ca01a7e1/packages/flutter_form_bloc/example/lib/forms/complex_login_form.dart#L75-L101)

**Comment by jatin-rajput** [comment]
yupppp my problem is solved thanks alot... best of luck for future....amazing package

**Comment by GiancarloCode** [comment]
Great.
Remember that in addition to the widgets offered by `flutter_form_bloc`, it is quite simple to make any widget react to the `FieldBloc` and update its value, so you will not have any limitation in the visual aspect (UI).
