### ISSUE TITLE
Update to bloc 5

### ISSUE THREAD

**Issue by Reprevise** [GiancarloCode/form_bloc#124]
This package should be updated to bloc 5.

**Comment by GiancarloCode** [comment]
Yes, the day after tomorrow I will update and review the PRs.

**Comment by davidAg9** [comment]
bro we are waiting

**Comment by GiancarloCode** [comment]
`flutter_form_bloc: ^0.15.0` is available. 🎉

**Comment by Reprevise** [comment]
@GiancarloCode How do we get the initial state of a field now?

**Comment by GiancarloCode** [comment]
@Reprevise the initial state is the first state of the bloc
https://github.com/felangel/bloc/blob/c7285fdd4e63fe17677f0e7af2d0ed09ade6edc1/packages/bloc/test/bloc_test.dart#L42-L46

**Comment by Reprevise** [comment]
We have to get it asynchronously now? We used to just be able to do FieldBloc#initialState.

**Comment by GiancarloCode** [comment]
@Reprevise  You can use `bloc.state` but use it before any events are added

```dart
      test('state returns correct value initially', () {
        expect(simpleBloc.state, '');
      });
```

**Comment by Reprevise** [comment]
Ah, but I'm using this in my `onSubmitting()` method to check whether a field has changed or not. Why'd you remove the `initialState` parameter in the first place?

**Comment by GiancarloCode** [comment]
It was removed in bloc 5, check [this](https://github.com/felangel/bloc/issues/1304) and if you think it is missing we can find an alternative

**Comment by GiancarloCode** [comment]
> I'm using this in my onSubmitting() method to check whether a field has changed or not.

it seems that it could be added as a property of the state and that the field bloc takes care of updating it, if you want to open an issue and write a feature request with more details, I could add it if it is viable, but it would be next week

**Comment by Reprevise** [comment]
Okay, I just found out about the `isInitial` property, so I'll be using that to check if a field has changed.

Since this package has been updated to bloc 5, this issue can now be closed.
