### ISSUE TITLE
issue related to issuecomment-613836269

### ISSUE THREAD

**Issue by rodriger06** [GiancarloCode/form_bloc#125]
Hi there,

I have a question related to solution provided in the link below using select_dialog
https://github.com/GiancarloCode/form_bloc/issues/64#issuecomment-613836269

I like the solution and it is very useful. however, i notice that the drop down menu doesnt have the text label in the middle like a regular textfield.  the textlable is already at the top of the drop down menu.  see pic attach
<img width="185" alt="dropdown" src="https://user-images.githubusercontent.com/49496303/86688722-5a77e400-bfd4-11ea-824d-7741a072dc85.PNG">

if you look at the attached image, the last field is the one you proposed using SelectDialogFieldBlocBuilder (link above).
however, the labeltext (dropdown with search) is appearing at the top without me tapping on it.  if you look at the other fields which are TextFieldBlocBuilder, the text label appear on the center. when i tap on those fieldd, then the textlabel move to the top of the textfield.  this is not happening for SelectDialogFieldBlocBuilder .  is this an issue?  how can i resolve this so the text label is at the center and when tap it can move to the top?

thanks in advance

**Comment by GiancarloCode** [comment]
@rodriger06 use `isEmpty` property of `InputDecorator` like [this widget](https://github.com/GiancarloCode/form_bloc/blob/314267636df540aceac75d58740923c4a6d1dc5b/packages/flutter_form_bloc/lib/src/dropdown_field_bloc_builder_mobile.dart#L194)  
```dart
isEmpty: state.value == null,
```

**Comment by rodriger06** [comment]
Thank you so much. This really helps. I hope you can integrate the select
dialog logic into a new type of text field in the future. Keep up the good
work. Looking forward to new enhancement.
