### ISSUE TITLE
Flutter SDK version error

### ISSUE THREAD

**Issue by UjjwaRaijada** [GiancarloCode/form_bloc#129]
on uploading the dependencies, it is show error "The current Flutter SDK version is 1.12.13+hotfix.8.". Below is the details error.

The current Flutter SDK version is 1.12.13+hotfix.8.

Because every version of flutter_form_bloc from path depends on flutter_bloc ^5.0.1 which depends on flutter_cubit ^0.1.0, every version of flutter_form_bloc from path requires flutter_cubit ^0.1.0.
And because flutter_cubit >=0.0.2 depends on provider ^4.1.3, every version of flutter_form_bloc from path requires provider ^4.1.3.
So, because provider >=4.1.0-dev+1 requires Flutter SDK version >=1.15.17-pre.5 and form_bloc_web depends on flutter_form_bloc from path, version solving failed.
pub get failed (1; So, because provider >=4.1.0-dev+1 requires Flutter SDK version >=1.15.17-pre.5 and form_bloc_web depends on flutter_form_bloc from path, version solving failed.)

**Comment by GiancarloCode** [comment]
You need to use a flutter version >= 1.15.17-pre.5
