### ISSUE TITLE
can't change font or textAlign for DateTimeFieldBlocBuilder

### ISSUE THREAD

**Issue by SogoGolf** [GiancarloCode/form_bloc#131]
hi, thanks for the great components.

can you add the ability to specify:
- TextStyle
- text alignment

for the ```DateTimeFieldBlocBuilder``` component ? 

At the moment we can't make this control fit into / match our UI. Many thanks.

![image](https://user-images.githubusercontent.com/19580787/87670268-cddadc00-c7b2-11ea-953d-ce1a67d0dfca.png)

**Comment by SogoGolf** [comment]
hi, any thoughts on this ?

**Comment by GiancarloCode** [comment]
Hello, sorry for the delay, I will review it tomorrow.
remember that when you are eager you can fork and edit the widget, and if you want to do the pull request

**Comment by Chralu** [comment]
Hi @GiancarloCode,

Here is a fix for that issue :  #181.

**Comment by SogoGolf** [comment]
hi, can we get this fix merged ?
