### ISSUE TITLE
Feature request: Autofill Support

### ISSUE THREAD

**Issue by SebastianKlaiber** [GiancarloCode/form_bloc#135]
After autofill is available in the beta channel, this library should support this feature too.

https://github.com/flutter/flutter/pull/52126

**Comment by Just66** [comment]
Waiting for that feature also

**Comment by SebastianKlaiber** [comment]
Any updates?

**Comment by WahdanZ** [comment]
fix in the latest version 

```
dependencies:
  form_bloc: ^0.20.0
  flutter_form_bloc: ^0.20.0
```
