### ISSUE TITLE
Date picker cupertino

### ISSUE THREAD

**Issue by ignaciolopez12** [GiancarloCode/form_bloc#137]
Hello, is there any way to implement the iOS Date picker? The material calendar is very ugly to be able to select the date of birth

**Comment by JulianSwales** [comment]
+1 Was just looking for this.. I'd like to have Cupertino on iOS and the standard on Android.

**Comment by ignaciolopez12** [comment]
> +1 Was just looking for this.. I'd like to have Cupertino on iOS and the standard on Android.

https://github.com/GiancarloCode/form_bloc/issues/64#issuecomment-613836269
