### ISSUE TITLE
How can I detect form has error?

### ISSUE THREAD

**Issue by sm2017** [GiancarloCode/form_bloc#139]
I want to disable submit button when form has error, How can I do this?

An awesome library in React ecosystem has many state properties https://final-form.org/docs/final-form/types/FormState#hassubmiterrors and is nice for inspiration

**Comment by sm2017** [comment]
@GiancarloCode  I found ` state.isValid()` But how  can  I render error `Text` while ` state.isValid()` is true? How can I get error text?

**Comment by maxpeterson** [comment]
Setting the `RaisedButton.onPressed` will disable it so you can disable it with something like this:  
```
                  RaisedButton(
                    onPressed: state.isValid() ? formBlock.submit : null,
                    child: Text('Sign in'),
                  ),
```

For adding additional `Text`, you should be able to add  the `Text` to your Widget **only** if `state.isValid()`

**Comment by sm2017** [comment]
@maxpeterson I asked something else!
I want to get the **error message**
i.e this field is required

**Comment by maxpeterson** [comment]
@sm2017 sorry - I misunderstood... are you referring to the text that is returned by a validation function and rendered by the field? ... maybe `email.state.error` where `email = TextFieldBloc` (with validators) ... or maybe I am still not understanding your issue!

**Comment by sm2017** [comment]
@maxpeterson thanks a lot
