### ISSUE TITLE
Clear text form without getting error message

### ISSUE THREAD

**Issue by bontew** [GiancarloCode/form_bloc#14]
I am using form_bloc and its working well until i have to clear text from Forms. While i try to clear text using nameField.updateValue("") or nameField.clear() i got error message "this field is required" at that form. How i cleared text without i got error message? sorry for my bad english

**Comment by GiancarloCode** [comment]
Hello, I fixed the `clear` method of `FieldBloc` in form_bloc v0.10.1. 😀

Each `Fieldbloc` has the [isInitial](https://pub.dev/documentation/form_bloc/latest/form_bloc/FieldBlocState/isInitial.html) and [canShowError](https://pub.dev/documentation/form_bloc/latest/form_bloc/FieldBlocState/canShowError.html) property.

You can use the `clear` method to eliminate the value of the` FieldBloc` and make `isInitial` to `true`, or you can also use the` updateInitialValue` method that also makes `isInitial` to `true`, but it will allow you to add the value you want.
