### ISSUE TITLE
Release for bloc 6.0.0

### ISSUE THREAD

**Issue by rfuerst87** [GiancarloCode/form_bloc#145]
Bloc 6.0.0 was released recently. Would it be possible to upgrade this library? TIA and keep up the good work!

**Comment by israellias** [comment]
+1

**Comment by ivatar39** [comment]
+1

**Comment by GiancarloCode** [comment]
I will publish a new version in a few hours

**Comment by GiancarloCode** [comment]
Since version 6.0.0 do not emit current state on subscriptions, several important changes must be made to ensure correct behavior of field blocs and form bloc, I'll try to finish it this weekend

**Comment by alejandroaap** [comment]
I have updated the form_bloc library to version 0.17.0 which includes updating the bloc library to version 0.6.0 and I have found that now the function isValid ([int step]) always returns false this did not happen before. Any suggestions as to why this may be happening?

On the other hand I take the opportunity to ask to see if someone can help me. I have tried creating a focus node for each field in the form but when these are embedded in widgets and new widgets with fields can be added I have not been able to make it work, I would like to see an example like the example 'List and group fields' using focusnode.

Thank you

**Comment by GiancarloCode** [comment]
`flutter_form_bloc: ^0.18.0` was released 🎉.

**Comment by alejandroaap** [comment]
Hi @GiancarloCode ,

I just updated to version 0.18.0 and I am seeing that the console is throwing the following error


```
[VERBOSE-2: ui_dart_state.cc (166)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
Receiver: null
Tried calling: call (Instance of 'FormBlocLoading <String, String>')
# 0 Object.noSuchMethod (dart: core-patch / object_patch.dart: 51: 5)
# 1 EmitLatestStateAddedMixin.listen.emitLatestStateAddedIfNeeded
package: form_bloc /… / utils / emit_latest_state_added_mixin.dart: 20
# 2 EmitLatestStateAddedMixin.listen. <Anonymous closure>
package: form_bloc /… / utils / emit_latest_state_added_mixin.dart: 31
# 3 _rootRunUnary (dart: async / zone.dart: 1198: 47)
# 4 _CustomZone.runUnary (dart: async / zone.dart: 1100: 19)
# 5 _FutureListener.handleValue (dart: async / future_impl.dart: 143: 18)
# 6 Future._propagateToListeners.handleValueCallback (dart: async / future_impl.dart: 696: 45)
# 7 Future._propagateToListeners (dart: async / future_impl.dart: 725: 32)
# 8 Future._complete (dart: async / future_impl.dart: 519: 7)
# 9 new Future.delayed. <Anonymous closure> (dart: async / futur <…>

```

Specifically, the code where this error is thrown is as follows:
```
    void emitLatestStateAddedIfNeeded () {
      if (! isLatestStateAddedEmitted) {
        onData ();
        isLatestStateAddedEmitted = true;
      }
    }
```
Any idea why this is happening?

**Comment by GiancarloCode** [comment]
@alejandroaap 

`flutter_form_bloc: ^0.19.0` was released 🎉.
