### ISSUE TITLE
Listen to changes

### ISSUE THREAD

**Issue by sm2017** [GiancarloCode/form_bloc#149]
@GiancarloCode
How can I listen to changes , not only a specific field , All changes in every fields in the form,

I want to implement auto save, when fields changes

I tried to use `BlocListener` but I don't know how can I be sure something changed

**Comment by alejandroaap** [comment]
I have a similar problem

**Comment by sm2017** [comment]
@alejandroaap Do you found any solution?

**Comment by GiancarloCode** [comment]
hello,
You can serialize the form, and listen the form state changes.

check https://giancarlocode.github.io/form_bloc/#/serialized_form_example

And this https://github.com/GiancarloCode/form_bloc/blob/ff919b574b4a1973cde1248ee3bdeb36cd9b4879/form_bloc_web/lib/examples/list_fields_form.dart#L77

**Comment by alejandroaap** [comment]
@GiancarloCode Hello, but this is not the solution to the problem presented here or at least I do not understand it as a solution. How can I make the moment a field of the form changes FormBlocListener to be executed? With the solution that you propose I should manually call state.toJson, to do that I don't need to serialize the form, manually I can already retrieve the values of the fields, what I want is for the form to listen to the changes in the fields.

**Comment by GiancarloCode** [comment]
@alejandroaap 
If it is business logic you can do it like this
```dart
MyFormBloc() {
    addFieldBlocs(fieldBlocs: [
      field1,
    ]);

    distinct(
      (previous, current) =>
          previous.toJson().toString() != current.toString().toString(),
    ).listen((state) {
      // Awesome logic
      print(state.toJson());
    });
  }
```
If is related to UI, you can use typical `BlocListener`
```dart
BlocListener<AllFieldsFormBloc, FormBlocState>(
  listenWhen: (previous, current) =>
      previous.toJson().toString() !=
      current.toString().toString(),
  listener: (context, state) {
    // awesome logic
    print(state.toJson().toString());
  },
  child:
```

**Comment by sm2017** [comment]
@GiancarloCode thanks a lot

**Comment by alejandroaap** [comment]
Thank you very much @GiancarloCode  for your help, this has solved my problem :)

**Comment by alejandroaap** [comment]
Thank you very much @GiancarloCode for your help. The second solution has solved my problem but the first solution you have proposed has not worked for me. The line print(state.toJson ()) is never executed; so the listening method doesn't work properly, any ideas why?

**Comment by alejandroaap** [comment]
The second solution has solved my problem but the first solution you have proposed has not worked for me. The line print (state.toJson ()) is never executed; so the listening method doesn't work properly, any ideas why?

@sm2017 Have you tried the first proposed solution?

   distinct (
       (previous, current) =>
           previous.toJson (). toString ()! = current.toJson (). toString (),
     ) .listen ((state) {
       // Awesome logic
       print (state.toJson ());
     });

**Comment by GiancarloCode** [comment]
@alejandroaap use form_bloc 0.15 and flutter_form_bloc 0.15.1

**Comment by GiancarloCode** [comment]
`flutter_form_bloc: ^0.18.0` was released 🎉.

**Comment by alejandroaap** [comment]
Hello @GiancarloCode , the code that you proposed to me I have tested with the versions that you have mentioned and it has not worked for me. Today I have updated to version 0.18.0 and it still doesn't work, just print (state.toJson ()) is executed; the first time of initiation of the listen and never again. Any idea what is happening?

**Comment by GiancarloCode** [comment]
@alejandroaap what about `flutter_form_bloc: ^0.19.0` ?

**Comment by alejandroaap** [comment]
Hi @GiancarloCode I just tried version 0.19.0 and now everything works :) I can already listen the changes and also the console error has been fixed. Thank you very much for your help. Regarding the issue https://github.com/GiancarloCode/form_bloc/issues/152 could you help me?

**Comment by sm2017** [comment]
@GiancarloCode I have a problem

`previous.toJson()` or `current.toJson()` is not same as your https://giancarlocode.github.io/form_bloc/#/serialized_form_example

my `toJson()` returns something like

```
{fe5ac2c0-e083-11ea-bafe-fd47f73779d3: , fe5dd000-e083-11ea-897d-4bfeeca18a47: true, fe5e1e20-e083-11ea-8af6-e5e333fe2867: RangeValues(0.0, 10000000.0), fe5e4530-e083-11ea-8019-a52675f1229d: true, fe5e4530-e083-11ea-92b5-6fc278932b12: RangeValues(0.0, 100000.0), fe5ee170-e083-11ea-bd3b-99f5c00470b6: []}
```

What is these `uuid`s? Why key are `uuid` and not my field's name?

` previous.toJson().toString() != current.toJson().toString()` is wrong for me , I have a switch , When I turn it on result is `true` but why I turn it off result of ` previous.toJson().toString() != current.toJson().toString()`  is `false` and `// awesome logic` is not runned!

I am using later version of your library

**Comment by sm2017** [comment]
@GiancarloCode Are you sure we must return `previous.toJson().toString() != current.toJson().toString()`?

I think we must return `previous.toJson().toString() == current.toJson().toString()`

` !=` has wrong and `==` is correct

**Comment by alejandroaap** [comment]
> @GiancarloCode Are you sure we must return `previous.toJson().toString() != current.toJson().toString()`?
> 
> I think we must return `previous.toJson().toString() == current.toJson().toString()`
> 
> ` !=` is wrong and `==` is correct

Yes, you are right, the correct solution is the one you propose. Thanks for the note :)
