### ISSUE TITLE
Add support for TextField.minLines

### ISSUE THREAD

**Issue by BreX900** [GiancarloCode/form_bloc#15]
`TextField.minLines` is supported only in `TextFieldBlocBuilder` but is not passed to `TextFieldConfiguration`.
However, it is not supported in `TypeAheadField` and in `TextFieldConfiguration`
Please add support

**Comment by GiancarloCode** [comment]
Thanks for reporting this, I fixed it in `flutter_form_bloc v0.10.2`. 🎉

**Comment by BreX900** [comment]
Thanks to you for the bug fix!
Instead, `TextField.readOnly` is intentionally unsupported?

**Comment by GiancarloCode** [comment]
No reason in particular, simply [flutter_typeahead](https://pub.dev/packages/flutter_typeahead) does not support them, tomorrow I add it and also I will add the other missing properties. 😁

**Comment by Danaru87** [comment]
Hello ;)
I need the read only property to :+1: .
Do you implement it for flutter_form_bloc v0.10.3 release ?

I forked your lib and added the readonly into TypeAheadField.dart and TextFieldBlocBuilder.
PR: https://github.com/GiancarloCode/form_bloc/pull/27

**Comment by GiancarloCode** [comment]
@Danaru87 hello
Yes, I have that implemented with the other missing properties of the text Field, and new widgets, I think I can release version 0.10.3 in a few hours I will release version 0.10.3 in a few hours when I get home :)

**Comment by Danaru87** [comment]
> @Danaru87 hello
> Yes, I have that implemented with the other missing properties of the text Field, and new widgets, I think I can release version 0.10.3 in a few hours I will release version 0.10.3 in a few hours when I get home :)

Thx ;)
