### ISSUE TITLE
Version 0.16.1 onContinue does not work

### ISSUE THREAD

**Issue by hamidhandid** [GiancarloCode/form_bloc#150]
I have a bug with version 0.16.1, when i press continue button nothing happend, after that when i press backspace it seems that onStepContinue is called. please fix this bug @GiancarloCode.
thanks.
![form_bloc](https://user-images.githubusercontent.com/43967256/88639436-08594880-d0d2-11ea-9c44-9a8917796913.gif)
![custom_form_bloc](https://user-images.githubusercontent.com/43967256/88639612-33439c80-d0d2-11ea-950a-b0c5c9810f3b.gif)

**Comment by alejandroaap** [comment]
I have also had this same problem when I have updated the pad versions. I have had to go back to previous versions, in addition another problem I have encountered is with the following https://github.com/GiancarloCode/form_bloc/issues/145#issuecomment-664347738

**Comment by GiancarloCode** [comment]
hello, use form_bloc 0.15.0 for now, which is the only one compatible with the latest version of flutter_form_bloc.

Yes, I noticed that this version has some errors even though the tests passed, so I did not release any version compatible with flutter_form_bloc, tomorrow I will fix it.

**Comment by alejandroaap** [comment]
@GiancarloCode Hello, but this is not the solution to the problem presented here or at least I do not understand it as a solution. How can I make the moment a field of the form changes FormBlocListener to be executed? With the solution that you propose I should manually call state.toJson, to do that I don't need to serialize the form, manually I can already retrieve the values of the fields, what I want is for the form to listen to the changes in the fields.

**Comment by GiancarloCode** [comment]
@alejandroaap  `flutter_form_bloc: ^0.18.0` was released 🎉.

**Comment by hamidhandid** [comment]
@GiancarloCode Thanks.
