### ISSUE TITLE
ListFieldBloc<BooleanFieldBloc>() is broken

### ISSUE THREAD

**Issue by egenita** [GiancarloCode/form_bloc#158]
Hi,

I've updated the package from v0.15.1 to v0.19.0 and my list of checkbox field is now broken.
It only display the first checkbox file in the list.
![image](https://user-images.githubusercontent.com/2075962/89617947-b4aee200-d8bd-11ea-91e0-6c4d6f40cba3.png)

Before the upgrade:
![image](https://user-images.githubusercontent.com/2075962/89620023-95b24f00-d8c1-11ea-871e-63f5bb8675b9.png)

**Comment by GiancarloCode** [comment]
Hi, update to `form_bloc: ^0.19.1`
So delete your `pubspec.lock` and then get dependencies again.

**Comment by egenita** [comment]
Wow! That was quick!
Yeah, it solves my problem.

Thank you!
