### ISSUE TITLE
Adding a field bloc doesn't call listener

### ISSUE THREAD

**Issue by Reprevise** [GiancarloCode/form_bloc#17]
I have a method that adds a `FieldBloc` to a path called 'teams'. If I were to remove the path parameter, thereby making it null, the state updates and when I print `state.fieldBlocs`, it returns the correct map but if I specify a path name and I click the button to call the function, nothing happens.

Here's the method that adds the `FieldBloc`:

```
  void addTeamField({String name}) {
    addFieldBloc(
      path: 'teams',
      fieldBloc: TextFieldBloc(
        name: 'teamName',
        initialValue: name ?? '',
        validators: [FieldBlocValidators.requiredTextFieldBloc],
      ),
    );
  }
```

I try to access it like this:

```
print(state.fieldBlocs);
final fields = state.fieldBlocFromPath('teams')?.asFieldBlocList;
```

but it always returns `null`. Why is that?

Is it because there's only one `FieldBloc` being added?

**Comment by GiancarloCode** [comment]
What do you mean with listener? `formBlocListener`?

In order to add a `fieldBloc` to a `path`, the parent must exist, so you must create it before.
```
    addFieldBloc (
       fieldBloc: FieldBlocList (name: 'teams', fieldBlocs: []),
     );
```
____

you can also omit null aware operator, so change this `initialValue: name ?? ''` to this `initialValue: name`,

**Comment by Reprevise** [comment]
Is that in the documentation? I must've missed it haha.

**Comment by GiancarloCode** [comment]
Apparently I omitted it, already add it to the docs of the new release :).

Initially I had thought that if the `path` did not exist it could be created automatically, but I decided not to do it since it seemed a little more logical that everything was more explicit, although I am still not sure.

**Comment by Reprevise** [comment]
To me it makes sense to just create it automatically if it doesn't exist like how Windows does it when you specify a path it'll just create all the sub directories. It makes it easier for the developer imo.

**Comment by GiancarloCode** [comment]
At the moment it is not possible since the parent field could be a `GroupFieldBloc` or a `ListFieldBloc`.
