### ISSUE TITLE
Adding images

### ISSUE THREAD

**Issue by davidcz95** [GiancarloCode/form_bloc#170]
Hello,
Is it possible to add a functionality of adding pictures to the form? From phone storage or opening camera directly?
It looks like this would be quite complicated...

**Comment by maxpeterson** [comment]
Is this relevant?  https://github.com/GiancarloCode/form_bloc/issues/57#issuecomment-609565908

**Comment by davidcz95** [comment]
@maxpeterson ;O Of course I don't know how I missed it, thanks!
