### ISSUE TITLE
Listener when onStepCancel

### ISSUE THREAD

**Issue by davidcz95** [GiancarloCode/form_bloc#171]
Hello,

I can't seem to find how can I listen for changes when cancel button is pushed when building wizard. My form is going back a step but how can I listen for it in FormBlocListener?

It is probably easy I just can't find it...

**Comment by tgbarker** [comment]
Hi @davidcz95 

When you are creating the StepperFormBlocBuilder

```
StepperFormBlocBuilder<WizardFormBloc>(
                    type: StepperType.horizontal,
                    physics: ClampingScrollPhysics(),
                    onStepCancel: (formBloc) {
                      log("Cancel clicked");
                      // 
                      // do stuff here
                      //
                      formBloc.previousStep();
                    },
                    controlsBuilder: (context, onStepContinue, onStepCancel, step, formBloc) {
```

You can see that you can override the onStepCancel function. Don't forget to call manually formBloc.previousStep(); at the end if you want to keep the back to previous step that is by default!

Hope this helps.

**Comment by davidcz95** [comment]
That's it, thank you!
