### ISSUE TITLE
Wizard Step skipping mechanism 

### ISSUE THREAD

**Issue by aaassseee** [GiancarloCode/form_bloc#174]
Is there any skipping mechanism in wizard? I would to skip some of the single choice steps depend on API call back.

**Comment by tgbarker** [comment]
See below some pseudo code
`
  bool skipStep1 = false;
  @override
  void onSubmitting() async {

  if(state.currentStep == 0){
     skipStep1 = callToApi();
     if(skipStep1) updateCurrentStep(2);
     emitSuccess();
  } else if(state.currentStep == 1){
     emitSuccess();
 } else if(state.currentStep==2){
    emitSuccess();
}
}`

The call to updateCurrentStep(2) will skip step 1 according to the result of call callToApi()

**Comment by aaassseee** [comment]
Thanks for helping, it works perfectly
