### ISSUE TITLE
Add an example of a field using BlocBuilder/BlocListener

### ISSUE THREAD

**Issue by Reprevise** [GiancarloCode/form_bloc#18]
It would be great if you could add an example (or add on to another example like the 'form_fields_example_form') of you using a `FieldBloc` such as `InputFieldBloc` to create a `DateTime` field or something using `BlocBuilder` or `BlocListener`.

**Comment by GiancarloCode** [comment]
hello, have you reviewed the [progress form](https://github.com/GiancarloCode/form_bloc/blob/master/packages/flutter_form_bloc/example/lib/forms/progress_form.dart)? it has a field for images.
In a few days add a `DateTimeFieldBlocBuilder` and you can check the code.
But basically it is.
1. Wrap the widget in `BlocBuilder`
2. Assign the value of the `fieldBloc` to the widget.
3. Update the value when the widget changes its value.

**Comment by GiancarloCode** [comment]
@Reprevise  check out https://github.com/GiancarloCode/form_bloc/issues/40

**Comment by Reprevise** [comment]
Thanks, I've created my own field.
