### ISSUE TITLE
Cupertino theme support

### ISSUE THREAD

**Issue by gavingolden** [GiancarloCode/form_bloc#186]
Does this have any basic Cupertino widget support out of the box? If so, is there any documentation on that topic and, if not, is there any way to work around that on my end?

I'm new to Flutter but my current understanding is that there are at least some common properties between the Material and Cupertino widgets. At the very least I'm hoping there's a way to use Cupertino widgets with those common properties. Ideally, I'd like to combine it with this: https://pub.dev/packages/flutter_platform_widgets

PS: this is a very helpful library so thanks for creating it 👍

**Comment by dJani97** [comment]
Right now I was wondering about the same thing. To anyone who finds this in the future, as of now this seems like the only solution: https://github.com/GiancarloCode/form_bloc/issues/64
