### ISSUE TITLE
TextFieldBlocBuilder ignores the obscureText argument

### ISSUE THREAD

**Issue by fabianMendez** [GiancarloCode/form_bloc#188]
Passing `obscureText: true` has no effect in the resulting input field, one have to pass:

```dart
suffixButton: SuffixButton.obscureText,
```

which is not always the desired effect.

Thanks

**Comment by Babwenbiber** [comment]
Duplicate of [this issue](https://github.com/GiancarloCode/form_bloc/issues/92#issue-622568815).

However, needs to be fixed.

**Comment by fabianMendez** [comment]
Ok, I will close this then, thank you
