### ISSUE TITLE
Is this project not maintained anymore?

### ISSUE THREAD

**Issue by vasilich6107** [GiancarloCode/form_bloc#192]
Do anyone know anything about future of this repo?
As far as it has decent amount of bugs and not actively maintained I'm moving to https://github.com/joanpablo/reactive_forms

**Comment by victorcatn** [comment]
@GiancarloCode has not talked about Flutter since August but he's still active in his Youtube channel (2 weeks ago) talking about unrelated themes. If for some reason he can't maintain the project, the comunity can continue maintaining this project but he did not specify the licence. 
I'm a newbie in Flutter and the first and only app that I made in Flutter is using form_bloc but in my opinion reactive_forms looks better in usability, documentation, flexibility and the maintainer seems to be very professional so I'll also consider moving to that library even if it's less known.

**Comment by vasilich6107** [comment]
Hi @victorcatn 
Thanks for additional info.

**Comment by ayushin** [comment]
@GiancarloCode can you let us know what you are up to? Lots of people using this in production, it would be great to have some clarity so we can plan accordingly.

**Comment by stwonary** [comment]
Packages' Licence is MIT License. 

https://github.com/GiancarloCode/form_bloc/blob/master/packages/form_bloc/LICENSE.MD
https://github.com/GiancarloCode/form_bloc/blob/master/packages/flutter_form_bloc/LICENSE.MD

**Comment by ayushin** [comment]
well, i've taken a look at https://github.com/joanpablo/reactive_forms and as much as I love form_bloc I think that library is actually superior and simpler and more powerful.

I think it would be a better spending of the time to write a guide or semi-automatic script to convert form_bloc to reactive_forms

**Comment by HathTech** [comment]
Hey, @ayushin Did you find time to write a script or something? 

Do share with us the details if possible.

**Comment by WahdanZ** [comment]
Hey, I able to migrate to Null safety, and I'm going to continue to support this package. 
check my  repo https://github.com/WahdanZ/form_bloc
you can use it 

```
  flutter_form_bloc:
    git:
      url: https://github.com/WahdanZ/form_bloc
      ref: ns-mirgrate
      path: packages/flutter_form_bloc
```

**Comment by vasilich6107** [comment]
@WahdanZ I would rather suggest you to join to our community of reactive_forms users.

the maintainer is very friendly, we develop a lot of component wrappers. Together we can do more.

**Comment by DJSL1NKY** [comment]
@WahdanZ If I read your Post, you are one of the maintainer of the reactive_forms Package, right?

If so, could you please help me to switch my Project from the form_bloc Package to the reactive_forms?

**Comment by vasilich6107** [comment]
@DJSL1NKY you can ask any questions about migration to reactive_forms here - https://github.com/joanpablo/reactive_forms/issues

**Comment by WahdanZ** [comment]
@vasilich6107 it seemed very impressive package, I'll try to look at it but the problem I have a production project that mainly depends on form_bloc so want to support it

**Comment by ayushin** [comment]
@WahdanZ We have it in production too, was a bit of a shock when @GiancarloCode just disappeared into thin air.

We'll be happy to help on a few issues as well if you take over.

**Comment by WahdanZ** [comment]
@ayushin I already did  Null safety migration 
https://github.com/GiancarloCode/form_bloc/pull/209
you can check it I'll be happy to support it
