### ISSUE TITLE
Theme of context shadowThemeOnly

### ISSUE THREAD

**Issue by aideric** [GiancarloCode/form_bloc#193]
../../.pub-cache/hosted/pub.dartlang.org/flutter_form_bloc-0.19.0/lib/src/dropdown.dart:844:34: Error: No named parameter with the name 'shadowThemeOnly'.
            theme: Theme.of(context, shadowThemeOnly: true),

Flutter version 1.24.0-10.2.pre

seems shadowThemeOnly removed

**Comment by cloudystef** [comment]
I suggested a pull request. I hope that this package won't die...

**Comment by Rajaee** [comment]
Is there any update on this issue?!

**Comment by vasilich6107** [comment]
@cloudystef I assume it already did this( 

Check this instead https://pub.dev/packages/reactive_forms
It even has tests with 96% of code coverage

**Comment by Rajaee** [comment]
@vasilich6107 is shifting to reactive forms difficult?

**Comment by vasilich6107** [comment]
@Rajaee it was pretty easy to me
Take into consideration the amount of forms and their complexity in your project.

If you have complex logic it will take you a little bit more time to migrate.
If you have only "login" like forms - it will be easier.

In any case the maintainer is very friendly and supportive.

**Comment by tgbarker** [comment]
@vasilich6107  just shifted and it wasnt too painful, with 2 forms and 6 elements in each. reactive_forms is agnostic of the state management framework used which is great, it is actively maintained and works with the latest version of flutter. I think reactive forms will be the library to use going forward, shame.

**Comment by vasilich6107** [comment]
@tgbarker its awesome!

**Comment by tk512** [comment]
A workaround until @GiancarloCode accepts the PR:

```
dependencies:
  flutter_form_bloc:
    git:
      url: git://github.com/cloudystef/form_bloc.git
      ref: bug-shadowThemeOnly
      path: packages/flutter_form_bloc
```

This basically gets the branch made by @cloudystef (thanks btw!) directly from the git branch, so it'll make your project work again until either it's fixed in flutter_form_bloc or if you change to another library.

I like reactive_forms as well but I think this library is easier to use, and also seems a bit faster on slower devices.

**Comment by vasilich6107** [comment]
@tk512 it seems that this project is discontinued.
Every issue or PR tags the author but with no luck.  We even know the real person behind this repo...
So we have no way contacting him to get any comments.
The last bit is that this library contains zero tests(

it was an awesome project earlier days...

**Comment by WahdanZ** [comment]
fix in the latest version 

```
dependencies:
  form_bloc: ^0.20.0
  flutter_form_bloc: ^0.20.0
```

**Comment by tk512** [comment]
@WahdanZ Is this project not dead after all?

**Comment by WahdanZ** [comment]
no ,you can check this https://github.com/GiancarloCode/form_bloc/issues/211

**Comment by tk512** [comment]
> no ,you can check this #211

Thanks!
