### ISSUE TITLE
Upgrade RxDart to 25.0.0

### ISSUE THREAD

**Issue by alejandroaap** [GiancarloCode/form_bloc#199]
Good afternoon,

Given that RxDart 25.0.0 has been released, when is this plugin going to be incorporated?

Thank you

**Comment by vasilich6107** [comment]
https://github.com/GiancarloCode/form_bloc/issues/192

**Comment by WahdanZ** [comment]
you can test the Prerelease versions that support null safety

```
dependencies:
  form_bloc: ^0.20.0-nullsafety.0
  flutter_form_bloc: ^0.20.0-nullsafety.0
  
```

**Comment by WahdanZ** [comment]
fix in the latest version 

```
dependencies:
  form_bloc: ^0.20.0
  flutter_form_bloc: ^0.20.0
```
