### ISSUE TITLE
[Question] More typings 

### ISSUE THREAD

**Issue by vasilich6107** [GiancarloCode/form_bloc#20]
Hi. Thanks for the package.
I'm curious are there any plans to add more types to eliminate the `access by random string`

Sample from the example app
```
print(state.fieldBlocFromPath('clubName').asTextFieldBloc.value);
    final members = state.fieldBlocFromPath('members').asFieldBlocList.map(
      (memberField) {
        return Member(
          firstName:
              memberField.asGroupFieldBloc['firstName'].asTextFieldBloc.value,
          lastName:
              memberField.asGroupFieldBloc['lastName'].asTextFieldBloc.value,
          hobbies: memberField.asGroupFieldBloc['hobbies'].asFieldBlocList
              .map((hobbyField) => hobbyField.asTextFieldBloc.value)
              .toList(),
        );
      },
    );
```

As far as we use `['firstName']` there is no type checking and could be a source of unexpected behaviour.

**Comment by GiancarloCode** [comment]
Hello, I would like you to show me how you would think the API should be, so I would have a better idea of what you expect :).

Currently the `FieldBlocs` are in the state of the `FormBloc` in the `Map <String, FieldBloc> fieldBlocs`.

Each `FieldBloc` is mapped with its `name` property.

* And `FieldBloc` is implemented by 3 classes:
  * `SingleFieldBloc` which is the base class of:
    * `InputFieldBloc`.
    * `TextFieldBloc`.
    * `BooleanFieldBloc`.
    * `SelectFieldBloc`.
    * `MultiSelectFieldBloc`.
  * `GroupFieldBloc` (`Map<String, FieldBloc>`).
  * `FieldBlocList` (`List<FieldBloc>`).

This allows  `Map <String, FieldBloc> fieldBlocs` to be like a JSON but typed.

JSON:
```
{
  "clubName": "Awesome Club",
  "members": [
    {
      "firstName": "John",
      "lastName": "Doe",
      "hobbies": [
        "Computer programming",
        "Animation"
      ]
    }
  ]
}
```
`Map <String, FieldBloc> fieldBlocs
```dart
{
    "clubName": TextFieldBloc(...),
    "members": FieldBlocList([
        GroupFieldBloc(
          {
              "firstName": TextFieldBloc(...),
              "lastName": TextFieldBloc(...),
              "hobbies": FieldBlocList([
                  TextFieldBloc(...),
                  TextFieldBloc(...)
              ])
          }
        )     
    ])
}
```

**Comment by GiancarloCode** [comment]
@vasilich6107 Hello, I still can't find an ideal way to add type but this is interesting https://github.com/GiancarloCode/form_bloc/issues/31

**Comment by GiancarloCode** [comment]
@vasilich6107 
In the new version `form_bloc` will be strong typed and will allow you to create forms with steps / wizard, I will publish it a couple of hours when the documentation is finished :)

**Comment by GiancarloCode** [comment]
@vasilich6107 Checkout the new API :)
https://giancarlocode.github.io/form_bloc/
