### ISSUE TITLE
UI not updated

### ISSUE THREAD

**Issue by sm2017** [GiancarloCode/form_bloc#200]
I am following **Async Feild Validation Example** and want to use `state.canShowIsValidating` or `state.isValidating`

When the async validator return error, UI is not updated and rendered with previous `state.canShowIsValidating` or `state.isValidating`  that is true

**Comment by sm2017** [comment]
@GiancarloCode it also set `state.canSubmit` to `false` When we have an async error, but changed again field and make it valid

**Comment by sm2017** [comment]
@GiancarloCode I found that it happens when I use `context.watch` instead of old syntax `context.bloc`, To reproduce bug in Async **Field Validation Example** use  `context.watch`

**Comment by sm2017** [comment]
@GiancarloCode Can you please reply

**Comment by vasilich6107** [comment]
hi. It seems that this project is not maintained anymore

https://github.com/GiancarloCode/form_bloc/issues/192
