### ISSUE TITLE
No named parameter with the name 'shadowThemeOnly'

### ISSUE THREAD

**Issue by rickyseezy** [GiancarloCode/form_bloc#208]
I can't even start the project .. Since I've upgraded Flutter SDK to latest version (Channel Stable).

Flutter version : 2.0.2

Flutter doctor : 

[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale en)
    • Flutter version 2.0.2 at /Users/rickyseezy/Documents/work/sdk/flutter
    • Framework revision 8962f6dc68 (5 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/rickyseezy/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 89.0.4389.82

• No issues found!

**Comment by bananagag** [comment]
Duplicated with #193

**Comment by AnanthGopal** [comment]
hi @rickyseezy ,

I got a similar issue, i clone their repository in my local and I remove shadowThemeOnly in the local clone project.

**Comment by vasilich6107** [comment]
Hi. It seems that this project is not maintained anymore 
https://github.com/GiancarloCode/form_bloc/issues/192

**Comment by WahdanZ** [comment]
Hey, I able to migrate to Null safety, and I'm going to continue to support this package.
check my repo https://github.com/WahdanZ/form_bloc
you can use it 

 ```
 flutter_form_bloc:
    git:
      url: https://github.com/WahdanZ/form_bloc
      ref: ns-mirgrate
      path: packages/flutter_form_bloc
```

**Comment by WahdanZ** [comment]
you can test the Prerelease versions that support null safety

```
dependencies:
  form_bloc: ^0.20.0-nullsafety.0
  flutter_form_bloc: ^0.20.0-nullsafety.0
  
```
