### ISSUE TITLE
Dependency on intl package

### ISSUE THREAD

**Issue by ebot64** [GiancarloCode/form_bloc#210]
I am not able to update other packages that depend on intl ^0.17.0 due to version incompatibility with flutter_form_bloc. 

```
Because flutter_form_bloc 0.19.0 depends on intl >=0.15.1 <0.17.0 and no versions of flutter_form_bloc 
match >0.19.0 <0.20.0, flutter_form_bloc ^0.19.0 requires intl >=0.15.1 <0.17.0.
So, because App_Name depends on both intl ^0.17.0 and flutter_form_bloc ^0.19.0, version solving failed.
```
I think its time flutter_form_bloc was updated.

**Comment by bobosette** [comment]
Me too....any solutions?

**Comment by ericklanford** [comment]
Same problem here :(

**Comment by DJSL1NKY** [comment]
same issue here, for me.

**Comment by vasilich6107** [comment]
Hi. It seems that this project is not maintained anymore 
https://github.com/GiancarloCode/form_bloc/issues/192

**Comment by WahdanZ** [comment]
you can test the Prerelease versions that support null safety

```
dependencies:
  form_bloc: ^0.20.0-nullsafety.0
  flutter_form_bloc: ^0.20.0-nullsafety.0
  
```

**Comment by bobosette** [comment]
oh perfect. Thank you

Il giorno gio 22 apr 2021 alle ore 12:33 Ahmed Wahdan <
***@***.***> ha scritto:

**Comment by WahdanZ** [comment]
fixed in latest version
