### ISSUE TITLE
I am looking for collaborators to help me maintain the project

### ISSUE THREAD

**Issue by GiancarloCode** [GiancarloCode/form_bloc#211]
Hello, first of all I apologize for not having updated the project these months, but for personal reasons I could not and in the near future I will not be able to do it either.

Therefore, if one or more of you are interested in maintaining the project or even improving it, for now it would be very helpful for the community that is currently making use of it.

So if you are interested, you can apply here by commenting:
**I want to be a collaborator**
 And answering these questions:

1. How much experience do you have programming and how much experience do you have programming in dart / flutter?

2. what do you do for a living? or what do you study?

3. Have you already made an update? If so, put the link of your fork, or pull request, so that I can review the code slightly (I say slightly because currently I cannot compile anything, but I can give me a good idea of ​​your knowledge of the framework and good practices)

4. What do you plan to do?

5. What vision do you have for the package? in case you have in mind to make groundbreaking changes that may be beneficial

6. Whatever you want.

I will be reviewing this thread these days, and if someone has suggestions to choose the collaborators you can tell me and I will update.

And in the same way, if a person applying has votes from other developers, it will also be taken into account.

If you are interested and you are chosen we can speak for discord to resolve or clarify any doubts about the code and of course to become a collaborator in the github project and also give you permission in pub.dev so that you can publish

___
I apologize again, and I really want to support and implement some things that I had in mind, but it will not be possible in the near future.

So for now, thank you very much if you want to help

**Comment by vasilich6107** [comment]
I suppose @WahdanZ could help

**Comment by WahdanZ** [comment]
I want to be happy to be a collaborator

- I have 4+ years of experience in mobile filed 
- I'm living in Egypt 
- I did this migration to null safety https://github.com/GiancarloCode/form_bloc/pull/209

**Comment by sm2017** [comment]
@GiancarloCode I'm glad you are well, just thanks for your awesome library

**Comment by rw152** [comment]
This an awesome library. I would be willing to support a patreon to keep this thing going.

**Comment by WahdanZ** [comment]
@GiancarloCode is there any update from your side?

**Comment by GiancarloCode** [comment]
Thanks for the support everyone.

@WahdanZ I chose you as a collaborator, so please write to my discord GiancarloCode#4227 and answer me here with your username to know that it is you.
And over there I clarify any questions regarding the publication of packages in pub or what you consider necessary, and of course thank you.

**Comment by WahdanZ** [comment]
@GiancarloCode this my discord Wahdan#5436

**Comment by GiancarloCode** [comment]
@WahdanZ are already an official Collaborator and he can keep the project updated in pub for now.
Thank you very much.

**Comment by aaassseee** [comment]
@GiancarloCode May I also be one of the collaborators?

**Comment by aaassseee** [comment]
@GiancarloCode Any progress or response?
