### ISSUE TITLE
Firebase error

### ISSUE THREAD

**Issue by ThereminB** [GiancarloCode/form_bloc#212]
Hi!!
I have a problem trying installing the library, I hope you could help me.
I looked everywhere but couldn't find anything

![image](https://user-images.githubusercontent.com/35237720/115319573-b798ec80-a145-11eb-925c-bee219d72e62.png)

**Comment by WahdanZ** [comment]
you can test the Prerelease versions that support null safety

```
dependencies:
  form_bloc: ^0.20.0-nullsafety.0
  flutter_form_bloc: ^0.20.0-nullsafety.0
  
```
