### ISSUE TITLE
[bug] extra data should be nullable

### ISSUE THREAD

**Issue by aaassseee** [GiancarloCode/form_bloc#214]
As the topic mentioned. Extra data should be dynamic and nullable in null safety version

**Comment by WahdanZ** [comment]
@aaassseee  it's already nullable, can you show me an example of what you said

**Comment by aaassseee** [comment]
for example by using the code in flutter_form_bloc

first update to the latest stable dart null safety version
``` yaml
environment:
  sdk: ">=2.12.4 <3.0.0"
```

then you will receive error on the builder lines
``` dart
TextFieldBlocBuilder(
  textFieldBloc: formBloc.text1,
  decoration: InputDecoration(
  labelText: 'TextFieldBlocBuilder',
  prefixIcon: Icon(Icons.text_fields),
 ),
),
```
```dart
textFieldBloc: formBloc.text1,
```

the line textFieldBloc: formBloc.text1 will emit an error because the bloc builder is using a injected bloc with Object as subtype 
``` dart
  /// {@template flutter_form_bloc.FieldBlocBuilder.fieldBloc}
  /// The `fieldBloc` for rebuild the widget
  /// when its state changes.
  /// {@endtemplate}
  final TextFieldBloc<Object> textFieldBloc;
```

by the documentation in [dart.dev](https://dart.dev/null-safety/understanding-null-safety#non-nullable-and-nullable-types), Object is not a nullable type so no matter how you define a nullable extra data type bloc, the builder would not accept the bloc with nullable type

moreover if we don't use the extra data type, it is uncompilable until we type something like this to fix the error
``` dart
final text1 = TextFieldBloc<Object>();
```

**Comment by WahdanZ** [comment]
thanks for your explanation, I'm working on it, it should be fixed in the next version today

**Comment by aaassseee** [comment]
thanks for your helping on the package.
I appreciate your effort to this package.

**Comment by WahdanZ** [comment]
you're most welcome, 
can you check this version before I release it 
```

dependencies:
  flutter_form_bloc: ^0.20.1-beta.0
```

**Comment by aaassseee** [comment]
I believe that dynamic include both Object and Object? So the question mark is redundant
``` dart
final TextFieldBloc<dynamic?> textFieldBloc;
```

**Comment by aaassseee** [comment]
In addition DateTimeFieldBlocBuilder and TimeFieldBlocBuilder is still using Object as extra data subtype

**Comment by WahdanZ** [comment]
fixed on 
```

dependencies:
  flutter_form_bloc: ^0.20.1-beta.1
```

**Comment by aaassseee** [comment]
LGTM
thanks for you time

**Comment by WahdanZ** [comment]
fixed on the latest release 

```
dependencies:
  form_bloc: ^0.20.1
```
