### ISSUE TITLE
 Null check operator used on a null value when using controlsBuilder 

### ISSUE THREAD

**Issue by AhmadMasri** [GiancarloCode/form_bloc#218]
Hello there, 
I have a project that is using form bloc with the wizard, everything was working fine before migrating to null safety, 
currently with the following settings: 
flutter_form_bloc: ^0.20.2
Flutter 2.2.0 
even when using the provided example on the documentation for using the controlsBuilder  it's giving  the following message  "Null check operator used on a null value"  
<img width="1049" alt="Screen Shot 2021-05-24 at 1 14 09 PM" src="https://user-images.githubusercontent.com/10615994/119333109-2829b080-bc92-11eb-8ba5-5e553c3e94e4.png">

               `   StepperFormBlocBuilder<ExaminationFormBloc>(
                    type: StepperType.horizontal,
                    controlsBuilder: (BuildContext context,
                        VoidCallback onStepContinue,
                        VoidCallback onStepCancel,
                        int step,
                        FormBloc formBloc) {
                      return Row(
                        children: <Widget>[
                          FlatButton(
                            onPressed: onStepContinue,
                            child: const Text('NEXT'),
                          ),
                          FlatButton(
                            onPressed: onStepCancel,
                            child: const Text('CANCEL'),
                          ),
                        ],
                      );
                    },
                    onStepTapped: (formbloc, step) {
                      ExaminationFormBloc x = formbloc as ExaminationFormBloc;
                      if (x.session.status > 2 ||
                          x.session.radiology == 2 ||
                          x.session.lab == 2) formbloc.updateCurrentStep(step);
                    },
                    stepsBuilder: (formbloc) {
                      List<FormBlocStep> list = [
                        stepInfo(formbloc, context),
                        stepGyno(formbloc, context),
                        stepDiagnosis(formbloc, context),
                        stepCase(formbloc, context),
                        stepPrescription(formbloc, context),
                        stepNonAvailable(formbloc, context),
                        stepAttachments(formbloc, context),
                      ];
                      return list;
                    },
                  );
                }`

**Comment by WahdanZ** [comment]
are there any logs you can share?

**Comment by AhmadMasri** [comment]
yes sure, 

`══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _CastError was thrown building Stepper-[<'__stepper_form_bloc_7__'>](dirty,
dependencies: [_LocalizationsScope-[GlobalKey#ef3c3], _EffectiveTickerMode, _InheritedTheme], state:
_StepperState#e2e26):
Null check operator used on a null value

The relevant error-causing widget was:
  Stepper-[<'__stepper_form_bloc_7__'>]
  file:///Users/as.masri/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_form_bloc-0.20.2/lib/src/stepper/stepper_form_bloc_builder.dart:169:16

When the exception was thrown, this was the stack:
#0      StepperFormBlocBuilder.build.<anonymous closure>.<anonymous closure> (package:flutter_form_bloc/src/stepper/stepper_form_bloc_builder.dart:196:61)
#1      _StepperState._buildVerticalControls (package:flutter_form_bloc/src/stepper/stepper.dart:358:37)
#2      _StepperState._buildHorizontal (package:flutter_form_bloc/src/stepper/stepper.dart:638:21)
#3      _StepperState.build (package:flutter_form_bloc/src/stepper/stepper.dart:666:16)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4553:5)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4737:11)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
...     Normal element mounting (9 frames)
#19     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (15 frames)
#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3360:20)
#36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#39     StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3350:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:16)
#42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4746:11)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
#44     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2582:33)
#45     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:875:21)
#46     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
#47     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#48     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#49     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#53     _invoke (dart:ui/hooks.dart:163:10)
#54     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
#55     _drawFrame (dart:ui/hooks.dart:126:31)
(elided 3 frames from dart:async)`

**Comment by WahdanZ** [comment]
can use this version 
`flutter_form_bloc: 0.20.3-dev`

and modify your code to this :
```   
StepperFormBlocBuilder<ExaminationFormBloc>(
                type: StepperType.horizontal,
                controlsBuilder: (BuildContext context,
                    VoidCallback? onStepContinue,
                    VoidCallback? onStepCancel,
                    int step,
                    FormBloc formBloc) {
                  return Row(
                    children: <Widget>[
                      FlatButton(
                        onPressed: onStepContinue,
                        child: const Text('NEXT'),
                      ),
                      FlatButton(
                        onPressed: onStepCancel,
                        child: const Text('CANCEL'),
                      ),
                    ],
                  );
                },
                onStepTapped: (formbloc, step) {
                  ExaminationFormBloc x = formbloc as ExaminationFormBloc;
                  if (x.session.status > 2 ||
                      x.session.radiology == 2 ||
                      x.session.lab == 2) formbloc.updateCurrentStep(step);
                },
                stepsBuilder: (formbloc) {
                  List<FormBlocStep> list = [
                    stepInfo(formbloc, context),
                    stepGyno(formbloc, context),
                    stepDiagnosis(formbloc, context),
                    stepCase(formbloc, context),
                    stepPrescription(formbloc, context),
                    stepNonAvailable(formbloc, context),
                    stepAttachments(formbloc, context),
                  ];
                  return list;
                },
              );
            }
``` 
`

**Comment by AhmadMasri** [comment]
> can use this version
> `flutter_form_bloc: 0.20.3-dev`
> 
> and modify your code to this :
> 
> ```
> StepperFormBlocBuilder<ExaminationFormBloc>(
>                 type: StepperType.horizontal,
>                 controlsBuilder: (BuildContext context,
>                     VoidCallback? onStepContinue,
>                     VoidCallback? onStepCancel,
>                     int step,
>                     FormBloc formBloc) {
>                   return Row(
>                     children: <Widget>[
>                       FlatButton(
>                         onPressed: onStepContinue,
>                         child: const Text('NEXT'),
>                       ),
>                       FlatButton(
>                         onPressed: onStepCancel,
>                         child: const Text('CANCEL'),
>                       ),
>                     ],
>                   );
>                 },
>                 onStepTapped: (formbloc, step) {
>                   ExaminationFormBloc x = formbloc as ExaminationFormBloc;
>                   if (x.session.status > 2 ||
>                       x.session.radiology == 2 ||
>                       x.session.lab == 2) formbloc.updateCurrentStep(step);
>                 },
>                 stepsBuilder: (formbloc) {
>                   List<FormBlocStep> list = [
>                     stepInfo(formbloc, context),
>                     stepGyno(formbloc, context),
>                     stepDiagnosis(formbloc, context),
>                     stepCase(formbloc, context),
>                     stepPrescription(formbloc, context),
>                     stepNonAvailable(formbloc, context),
>                     stepAttachments(formbloc, context),
>                   ];
>                   return list;
>                 },
>               );
>             }
> ```
> 
> `

that's works perfectly, thanks 🙏
