### ISSUE TITLE
Null check operator used on a null value when adding addAsyncValidators to InputFieldBloc

### ISSUE THREAD

**Issue by AhmadMasri** [GiancarloCode/form_bloc#219]
I have created a custom file uploader form field using InputFieldBloc and added addAsyncValidators, everything was working fine before migrating to null safety. now I'm getting the fallowing error: 

Unhandled Exception: Null check operator used on a null value
E/flutter (10356): #0      SingleFieldBloc._setUpAsyncValidatorsSubscription.<anonymous closure> (package:form_bloc/src/blocs/field/field_bloc.dart:566:28)
E/flutter (10356): #1      _SwitchMapStreamSink.add (package:rxdart/src/transformers/switch_map.dart:15:33)
E/flutter (10356): #2      forwardStream.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:rxdart/src/utils/forwarding_stream.dart:33:49)
E/flutter (10356): #3      forwardStream.runCatching (package:rxdart/src/utils/forwarding_stream.dart:23:12)
E/flutter (10356): #4      forwardStream.<anonymous closure>.<anonymous closure> (package:rxdart/src/utils/forwarding_stream.dart:33:28)
E/flutter (10356): #5      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (10356): #6      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (10356): #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (10356): #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (10356): #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (10356): #10     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378:25)
E/flutter (10356): #11     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244:5)
E/flutter (10356): #12     Subject._add (package:rxdart/src/subjects/subject.dart:141:17)
E/flutter (10356): #13     Subject.add (package:rxdart/src/subjects/subject.dart:135:5)
E/flutter (10356): #14     _BackpressureStreamSink.resolveWindowEnd (package:rxdart/src/transformers/backpressure/backpressure.dart:214:14)
E/flutter (10356): #15     _BackpressureStreamSink.singleWindow.<anonymous closure> (package:rxdart/src/transformers/backpressure/backpressure.dart:155:27)
E/flutter (10356): #16     _rootRun (dart:async/zone.dart:1346:47)
E/flutter (10356): #17     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (10356): #18     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (10356): #19     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:394:13)
E/flutter (10356): #20     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:404:15)
E/flutter (10356): #21     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
E/flutter (10356): #22     _TakeStream._handleData (dart:async/stream_pipe.dart:314:14)
E/flutter (10356): #23     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (10356): #24     _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (10356): #25     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (10356): #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (10356): #27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (10356): #28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (10356): #29     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter (10356): #30     _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter (10356): #31     _StreamController.add (dart:async/stream_controller.dart:554:5)
E/flutter (10356): #32     TimerStream._buildController.<anonymous closure>.<anonymous closure> (package:rxdart/src/streams/timer.dart:51:22)
E/flutter (10356): #33     _rootRun (dart:async/zone.dart:1346:47)
E/flutter (10356): #34     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (10356): #35     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (10356): #36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (10356): #37     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (10356): #38     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (10356): #39     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1186:23)
E/flutter (10356): #40     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (10356): #41     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (10356): #42     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (10356): #43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

flutter :2.2.0
flutter_form_bloc: 0.20.3-dev

My code is 
`
  final InputFieldBloc<File, void> file;
  
  
 file.addAsyncValidators([
      uploadPhoto,
    ]);
    
    Future<String> uploadPhoto(File sourceFile) async {
    if (fileUrl.value.isNotEmpty) return null;
    try {
      AttachmentItem attachmentItem =
          await imageRepository.uplaodImage(sourceFile, session);

      if (attachmentItem.url.length > 0) {
        fileUrl.updateValue(attachmentItem.url);
        fileName.updateValue(attachmentItem.fileName);
        return null;
      } else
        throw Exception("Unknown Error");
    } catch (e) {
      print(e);
      return e.toString();
    }
  }
`

**Comment by WahdanZ** [comment]
thanks for reporting, I'll consider it next release

**Comment by WahdanZ** [comment]
you can check the latest version :
` form_bloc: ^0.20.4
`
