### ISSUE TITLE
Can't define an initial value for TextFieldBlocBuilder

### ISSUE THREAD

**Issue by dtaskai** [GiancarloCode/form_bloc#229]
After going through the documentation I could not find a way to set an initial value to a TextField which is kind of surprising since we can make a TextField read only but can not set a default or initial value.

**Comment by dtaskai** [comment]
To specify I am looking for a way to set the initial value from the presentation layer to supply the value from a database and not set it in the bloc itself.

**Comment by GiancarloCode** [comment]
hello, you can use `field.updateInitialValue('value')` from anywhere, maybe initialState of your widget, but is better have all this logic in the bloc.

https://github.com/GiancarloCode/form_bloc/blob/master/form_bloc_web/lib/examples/loading_and_initializing_form.dart#L41

**Comment by dtaskai** [comment]
After a few workarounds I was able to solve my problem with the way you posted. Thanks for the quick reply.
