### ISSUE TITLE
Unexpected type migration

### ISSUE THREAD

**Issue by vasilich6107** [GiancarloCode/form_bloc#231]
In this code 

```
class InputFieldBloc<Value, ExtraData> extends SingleFieldBloc<Value?, Value,
    InputFieldBlocState<Value, ExtraData?>, ExtraData?> {
```

`ExtraData` transforms into `ExtraData?` without any reason...

Could you explain this behaviour?

**Comment by WahdanZ** [comment]
the ExtraData should be optional and can be nullable so that's why we make it `ExtraData?` .
but there is a problem with the current code and it should be like the below one, 
I'll update it and upload a new version of the package 
```
class InputFieldBloc<Value, ExtraData> extends SingleFieldBloc<Value?, Value,
    InputFieldBlocState<Value, ExtraData>, ExtraData?>
```
