### ISSUE TITLE
[Bug] hasFailureResponse should check value instead of type.

### ISSUE THREAD

**Issue by danielmahon** [GiancarloCode/form_bloc#24]
Looks like maybe an autocomplete typo, I'm assuming this (and probably other getters) should be referencing the value and not the type? Causes `state.hasFailureResponse` to always be true.

https://github.com/GiancarloCode/form_bloc/blob/b5f51e45cdf94c5101aee2bf15f0bc375a0dc63e/packages/form_bloc/lib/src/blocs/form/form_state.dart#L595

should be...

```dart
 bool get hasFailureResponse => failureResponse != null; 
```

**Comment by GiancarloCode** [comment]
Thanks for reporting this.

Fixed in form_bloc 0.10.3.
