### ISSUE TITLE
[Question] Populate Dropdown list from json from api

### ISSUE THREAD

**Issue by jawadsahil** [GiancarloCode/form_bloc#25]
Is there a way to populate a SelectFieldBloc from the json returned from API. I have a 

    Future<List<String>> itemsList 

in my Repository class. But I can not assign it to items.

    fieldBloc: SelectFieldBloc(
        name: 'circuitId',
        items: Repository.itemsList,
      ),

**Comment by GiancarloCode** [comment]
Hello,
1) Set `isLoading` to `true` in the `super` constructor
2) Implement `onLoading`
3) Add fields in `onLoading`
4) yield `state.toLoaded()` when you finish performing asynchronous functions.

```dart
class MyFormBloc extends FormBloc<String, String> {
  MyFormBloc() : super(isLoading: true);

  @override
  Stream<FormBlocState<String, String>> onLoading() async* {
    addFieldBloc(
      fieldBloc: SelectFieldBloc<String>(
        name: 'select',
        items: await _getItemsFromApi(),
      ),
    );

    yield state.toLoaded();
  }

  Future<List<String>> _getItemsFromApi() async {
    return ['Option A', 'Option B'];
  }

  @override
  Stream<FormBlocState<String, String>> onSubmitting() async* {
    // Awesome logic...
  }
}
```

You can check this example: [bloc](https://github.com/GiancarloCode/form_bloc/blob/master/packages/flutter_form_bloc/example/lib/forms/complex_async_prefilled_form_bloc.dart) - [ui](https://github.com/GiancarloCode/form_bloc/blob/master/packages/flutter_form_bloc/example/lib/forms/complex_async_prefilled_form.dart)

Although this example is not yet updated to make optimal use of the latest version (these days I will do it :)), there you can see how to handle the user interface in case you do not have internet when making the request.

**Comment by jawadsahil** [comment]
Hello, Sorry to reopen this again. I have a related question.

     items: await _getItemsFromApi(),

Sometimes due to some issues, the items are not fetched. So I have a button to reload/retry the same call to populate the drop-down again. How to achieve that? 

I called the     

    _formBloc.reload();

on the retry button tap. But this does not populate the dropdown.

**Comment by GiancarloCode** [comment]
You need to override `onReload`
https://github.com/GiancarloCode/form_bloc/blob/59d7842690353d67e8576856d5814535147ed14c/packages/flutter_form_bloc/example/lib/forms/complex_async_prefilled_form_bloc.dart#L20

Although perhaps it makes sense that when reload is called `onLoading` it is called again.

What do you think? Do you think there is a case in which those 2 logic can be different (load/ reload) ? 
At the moment I think not, if so I will make the change

P.D, I will launch the new version today,

Please check this: https://github.com/GiancarloCode/form_bloc/issues/37

**Comment by jawadsahil** [comment]
In my case, both onLoading and onReload has the same logic.

Wishing the best of luck for the new version. I will check the issue 37 in a while.

**Comment by moriswala** [comment]
I was looking for async pre-filled dropdown example. I tried to see the example link you provided earlier but https://github.com/GiancarloCode/form_bloc/blob/master/packages/flutter_form_bloc/example/lib/forms/complex_async_prefilled_form_bloc.dart

Unfortunately link is broken. Can you please provide example of it. Thank you.

**Comment by GiancarloCode** [comment]
@moriswala this is a demo and tutorial
https://giancarlocode.github.io/form_bloc/#/loading_and_initializing_example

This the full code
https://github.com/GiancarloCode/form_bloc/blob/master/form_bloc_web/lib/examples/loading_and_initializing_form.dart
