### ISSUE TITLE
Mark form as invalid by default

### ISSUE THREAD

**Issue by Almighty-Alpaca** [GiancarloCode/form_bloc#273]
Hi,

I'm using a form with `autoValidate = true` together with `isValid()` to trigger the state of my submit button. The problem I'm facing is that when loading the form, it is marked as valid for a split second, which causes the button to be active, before the fields are actually validated for the first time.

As I know that the form will be invalid by default (I have required fields) it would be really helpful to be able to mark the form as invalid by default.

I'm not sure if this would work correctly (I'm not familiar with the multistep forms) but my proposal would be to:
 - Add an `isInitiallyValid` parameter to `FormBloc` (default with `true` to not break anything)
 - Depending on the value set `isValidByStep` of `FormBlocState` to `{0: false}` initially

**Comment by aaassseee** [comment]
Are there any example for us to identify your problem?
Moreover are you wrapping your submit button with bloc builder to prevent the form submission when form state state.canSubmit && state.isValid()

**Comment by Almighty-Alpaca** [comment]
I've added a recording and attached the code of my login button and the FormBloc I'm using. I hope that helps to clarify the issue I'm having.

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/15787444/147883305-76e9d8c6-d94a-437c-8207-d6266664bb21.mp4
</details>

<details>
<summary>LoginButton</summary>

```dart
class LoginButton extends StatelessWidget {
  const LoginButton({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final bloc = context.watch<PasswordLoginFormBloc>();

    return bloc.state.canSubmit
        ? ElevatedButton(
            onPressed: bloc.state.isValid() ? bloc.submit : null,
            style: ElevatedButton.styleFrom(
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(30),
              ),
              primary: const Color(0xffffD600),
            ),
            child: const Text('Login'),
          )
        : const CircularProgressIndicator();
  }
}
```
</details>

<details>
<summary>PasswordLoginFormBloc</summary>

```dart
class PasswordLoginFormBloc extends FormBloc<void, String> {
  PasswordLoginFormBloc(this._authenticationRepository)
      : super(autoValidate: true) {
    addFieldBlocs(fieldBlocs: [email, password]);
  }

  final email = TextFieldBloc<void>(
    name: 'email',
    validators: [
      FieldBlocValidators.required,
      CustomFieldBlocValidators.email,
    ],
  );

  final password = TextFieldBloc<void>(
    name: 'password',
    validators: [
      FieldBlocValidators.required,
    ],
  );

  final AuthenticationRepository _authenticationRepository;

  @override
  Future<void> onSubmitting() async {
    try {
      await _authenticationRepository.logInWithEmailAndPassword(
        email: email.value,
        password: password.value,
      );

      emitSuccess(canSubmitAgain: false);
    } on LogInWithEmailAndPasswordFailure catch (e) {
      emitFailure(failureResponse: e.message);
    } catch (_) {
      emitFailure();
    }
  }
}
```
</details>

**Comment by aaassseee** [comment]
you can change the login button and give it a try
```dart 
onPressed: bloc.canSubmit && bloc.state.isValid() ? bloc.submit : null,
```

**Comment by aaassseee** [comment]
If you are talking about the visual effect but not the actual onPressed function can be pressed or not, then I am also facing this problem.

**Comment by Almighty-Alpaca** [comment]
Yes, I'm talking about the visual effect. It's implicitly controlled by `bloc.state.isValid()` in my example because buttons are automatically disabled (greyed out) when `onPressed == null`

**Comment by BreX900** [comment]
This problem will no longer exist with the next release of FormBloc using Cubit

Temporary solution not tested: 
- Mark the FormBloc in `isLoading: true`
- Add the fieldBlocs
- Emit `emitLoaded ()`

**Comment by Almighty-Alpaca** [comment]
Thanks, @BreX900. I can confirm that your proposed solution works 👍
