### ISSUE TITLE
updateExtraData not re-rendering ui

### ISSUE THREAD

**Issue by Ezrabeer** [GiancarloCode/form_bloc#289]
I'm not sure if this is a bug or intended, but I have a select field:
```dart
final SelectFieldBloc<SomeModel, bool> selectField = SelectFieldBloc(validators: [
  Validators.requiredSelectFieldBloc,
]);
```

then in the constructor:
```dart
selectField.onValueChanges(onData: (previous, current) async* {
  if (current.value!.isNotEmpty) {
    selectField.updateExtraData(true);
  }
});
```

This however doesn't seem to re-render the ui. The only way I got it working was to add a random field bloc (that isn't being used on the screen) in the if statement.

EDIT:
This was never answered on #163.

**Comment by WahdanZ** [comment]
can you show me the widget part?

**Comment by Ezrabeer** [comment]
Closing as I'm pretty sure this was related to #290.
