### ISSUE TITLE
[BUG]? Radio group does not select initial value when map<String, String> is used

### ISSUE THREAD

**Issue by jawadsahil** [GiancarloCode/form_bloc#29]
When you add the field as follows:

    addFieldBloc(
      fieldBloc: SelectFieldBloc<Map<String, String>>(
        name: 'bench',
        initialValue: {'key': 'A', 'value': 'All Benches'},
        validators: [FieldBlocValidators.requiredSelectFieldBloc],
        items: [
          {'key': 'A', 'value': 'All Benches'},
          {'key': 'S', 'value': 'Single Bench'},
          {'key': 'D', 'value': 'Division Bench'},
        ],
      ),
    )

and ui code

    RadioButtonGroupFieldBlocBuilder<Map<String, String>>(
                        canDeselect: false,
                        selectFieldBloc: state.fieldBlocFromPath('bench'),
                        itemBuilder:
                            (BuildContext context, Map<String, String> bench) {
                          return bench["value"];
                        },
                      )

I would expect the first radio button to be selected by default. But it is not! Also, the validators do not seem to work too for this field.

**Comment by GiancarloCode** [comment]
Thanks for reporting, I will review it in a few hours.

while why do you use a `Map<String, String>`? Do you use it to show the value in the UI?

**Comment by jawadsahil** [comment]
Thanks @GiancarloCode .. that is really nice of you.
