### ISSUE TITLE
TextStyle cannot change text color in TextFieldBlocBuilder

### ISSUE THREAD

**Issue by aideric** [GiancarloCode/form_bloc#294]
In the latest flutter form bloc
```
flutter_form_bloc: ^0.30.1
```
The text style cannot change the color of TextFieldBlocBuilder
```dart
                      TextFieldBlocBuilder(
                        textFieldBloc: formBloc.text1,
                        decoration: const InputDecoration(
                          labelText: 'TextFieldBlocBuilder textStyle red',
                          prefixIcon: Icon(Icons.text_fields),
                        ),
                        textStyle: TextStyle(color: Colors.red),
                      ),
                      TextFieldBlocBuilder(
                        textFieldBloc: formBloc.text1,
                        decoration: const InputDecoration(
                          labelText: 'TextFieldBlocBuilder textColor red',
                          prefixIcon: Icon(Icons.text_fields),
                        ),
                        textColor: MaterialStateProperty.all(Colors.red),
                      ),
```
you can add this code to https://github.com/GiancarloCode/form_bloc/blob/60521fc4d39d3b2f6acc27befcb7dbb6f3c9f568/packages/flutter_form_bloc/example/lib/main.dart#L179 to test it 

However, the textColor can change it.
Maybe need a migration guide for the user to migrate text style color to text color or fix it.

**Comment by WahdanZ** [comment]
textColor is used to customize the color of the text, but textStyle is used to customize fontSize, weight, and other attributes.

**Comment by aideric** [comment]
Thank you.
I just want to point out that in the old version, we can set text color by textStyle color. But in the new version we can't.
I think we should provide migration guide to the users.
