### ISSUE TITLE
Compatibility with the newest bloc package

### ISSUE THREAD

**Issue by owczaro** [GiancarloCode/form_bloc#3]
Your package is very useful! But it is incompatible with bloc ^2.0.0. Can U please solve this?

**Comment by GiancarloCode** [comment]
Hello, I'm glad you find it useful, I'll upload a new version in the next few days.

**Comment by huang12zheng** [comment]
🤣waiting for you

**Comment by ayushin** [comment]
its version 3.0.0 now :-)

**Comment by GiancarloCode** [comment]
@ayushin Sorry for the delay, flutter_form_bloc 0.6.0 is compatible with bloc 0.3.1 🎉
