### ISSUE TITLE
Dropdown..Builder add support for hintText

### ISSUE THREAD

**Issue by BreX900** [GiancarloCode/form_bloc#30]
Is it possible to add support for [`InputDecoration.hintText`, `InputDecoration.labelText`] to `DropdownFieldBlocBuilder`?
Right now. If we set in `InputDecoration.hintText` with a value the `DropdownFieldBlocBuilder` will not show the `InputDecoration.hintText` value. When no value is selected

**Comment by GiancarloCode** [comment]
Hello
Added in `flutter_form_bloc: 0.10.5`.

**Comment by BreX900** [comment]
Thanks so much for adding support for `hintText` but support for `labelText` is missing.
`LabelText` is shown as if it were a `hintText` when the `hintText` value is not set and the selected value is null
```
final hintText = widget.decoration.hintText ?? widget.decoration.labelText;
//...
DropdownButton<Value>(
  callOnPressed: _onPressedController.stream,
  value: fieldState.value,
  disabledHint: fieldState.value != null
                          ? widget.itemBuilder(context, fieldState.value)
                          : hintText != null
                              ? hintText 
                              : null,
//...
if (fieldState.value == null && hintText  != null) {
  return Text(
    hintText ,
//...
```

**Comment by GiancarloCode** [comment]
@BreX900 
I think that's the right behavior, the label text is displayed in the same position as the hint text in that case, just change the style.
This is how it works in text fields, although there is not much information regarding the hint text in the drop down menu, I use the same style as the text field
https://material.io/components/text-fields/#filled-text-field
https://material.io/components/menus/#exposed-dropdown-menu
https://material-components.github.io/material-components-web-catalog/#/component/select

... but maybe I'm wrong :). So I stay tuned

And if you want the label text to be placed at the top, you can assign an empty string to the hint text `''`

**Comment by BreX900** [comment]
https://material.io/components/text-fields/#filled-text-field
As you can see from the link you sent. labelText is shown as if it were a hintText. Even if hintText is absent.
This also works in TextFields

**Comment by GiancarloCode** [comment]
Mmm, as you showed me in the picture is how it behaves, maybe I'm not understanding you 😥

**Comment by BreX900** [comment]
Sorry. My mistake
Thank you so much and sorry for making you waste time

**Comment by GiancarloCode** [comment]
@BreX900  There is no problem :), it would be useful for you to give your opinion in pinned issues ;).
