### ISSUE TITLE
Submit can be called with invalid fields

### ISSUE THREAD

**Issue by MatyasK** [GiancarloCode/form_bloc#301]
When calling bloc.submit() it will emit a submitting state even when the fields are invalid, and then the app stuck in loading state as the bloc onSubmitting doesn't get fired, this can be reproduced in the website as well.

**Comment by MatyasK** [comment]
state.cansubmit is always true even when the form is actually invalid!

**Comment by aaassseee** [comment]
There is a new state in listener onSubmissionFailed when calling submit() during form is invalid.

> state.cansubmit is always true even when the form is actually invalid!

I don't think it make sense with normal use case.

**Comment by MatyasK** [comment]
Yeah onSubmissionFailed  has the expected result, however it would be nice if it will be added in the documentation as well.

**Comment by aaassseee** [comment]
Sure will do
