### ISSUE TITLE
i am here! printed in the console

### ISSUE THREAD

**Issue by jakuste136** [GiancarloCode/form_bloc#311]
Hi there. Is it possible to remove ```print('i am here!');``` from ```_TextFieldBlocBuilderState```. The log's getting really dirty with larger forms. Thanks in advance - you're doing great job!

**Comment by aaassseee** [comment]
Hi @jakuste136. After scanning the whole project. There isn't any lines of ```print('i am here!');``` shows up with any packages. Please check you code.

**Comment by jakuste136** [comment]
That's the version from my local pub cache (changed the extension to .txt)
[text_field_bloc_builder.txt](https://github.com/GiancarloCode/form_bloc/files/8858453/text_field_bloc_builder.txt)

**Comment by jakuste136** [comment]
Ok, after clearing local pub cache the print is gone. Sorry for the mess...
