### ISSUE TITLE
Custom state

### ISSUE THREAD

**Issue by 538023** [GiancarloCode/form_bloc#316]
First of all we need this:
https://github.com/GiancarloCode/form_bloc/pull/315
Than also _toJson:
![grafik](https://user-images.githubusercontent.com/83300538/178107307-d772a86f-5e1f-4213-b7d7-6c157ba4262c.png)

**Comment by aaassseee** [comment]
Miss/Sir before you open a pull request can you explain about what you target are you aiming. And why you are going to do that. I saw you export all the classes to user in #315. If a class is not expose to user there is always a reason. May you briefly explain what you want to achieve?

**Comment by aaassseee** [comment]
> @aaassseee I looked in "TextFieldBlocBuilder" to see how these are implemented as there were no instructions on how to create custom fields. If there is another way, is there an example?



> @aaassseee
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:flutter_form_bloc/flutter_form_bloc.dart';
> import 'package:wifi_iot/wifi_iot.dart';
> 
> import 'wifi.dart';
> import 'wifi_list.dart';
> import 'password_dialog.dart'
> 
> class WifiData {
>   Wifi wifi;
>   String password;
>   WifiData(this.wifi, this.password);
> }
> 
> class WifiSetupBlocState<ExtraData> extends FieldBlocState<WifiData?, WifiData?, ExtraData?> {
>   final dynamic Function(WifiData? value) _toJson;
>   WifiSetupBlocState({
>     required bool isValueChanged,
>     required WifiData? initialValue,
>     required WifiData? updatedValue,
>     required WifiData? value,
>     required Object? error,
>     required bool isDirty,
>     required Suggestions<WifiData?>? suggestions,
>     required bool isValidated,
>     required bool isValidating,
>     FormBloc? formBloc,
>     required String name,
>     List additionalProps = const <dynamic>[],
>     dynamic Function(WifiData? value)? toJson,
>     ExtraData? extraData,
>   }) : _toJson = toJson ?? ((value) => value), super(
>     isValueChanged: isValueChanged,
>     initialValue: initialValue,
>     updatedValue: updatedValue,
>     value: value,
>     error: error,
>     isDirty: isDirty,
>     suggestions: suggestions,
>     isValidated: isValidated,
>     isValidating: isValidating,
>     formBloc: formBloc,
>     name: name,
>     toJson: toJson,
>     extraData: extraData,
>   );
> 
>   @override
>   WifiSetupBlocState<ExtraData> copyWith({
>     bool? isValueChanged,
>     Param<WifiData?>? initialValue,
>     Param<WifiData?>? updatedValue,
>     Param<WifiData?>? value,
>     Param<Object?>? error,
>     bool? isDirty,
>     Param<Suggestions<WifiData?>?>? suggestions,
>     bool? isValidated,
>     bool? isValidating,
>     Param<FormBloc?>? formBloc,
>     Param<ExtraData?>? extraData,
>   }) {
>     return WifiSetupBlocState(
>       isValueChanged: isValueChanged ?? this.isValueChanged,
>       initialValue: initialValue.or(this.initialValue),
>       updatedValue: updatedValue.or(this.updatedValue),
>       value: value == null ? this.value : value.value,
>       error: error == null ? this.error : error.value,
>       suggestions: suggestions == null ? this.suggestions : suggestions.value,
>       isDirty: isDirty ?? this.isDirty,
>       isValidated: isValidated ?? this.isValidated,
>       isValidating: isValidating ?? this.isValidating,
>       formBloc: formBloc == null ? this.formBloc : formBloc.value,
>       name: name,
>       toJson: _toJson,
>       extraData: extraData == null ? this.extraData : extraData.value,
>     );
>   }
> }
> 
> class WifiSetupBloc<ExtraData> extends SingleFieldBloc<WifiData?, WifiData?, WifiSetupBlocState<ExtraData>, ExtraData?> {
>   WifiSetupBloc({
>     String? name,
>     WifiData? initialValue,
>     List<Validator<WifiData?>>? validators,
>     List<AsyncValidator<WifiData?>>? asyncValidators,
>     Duration asyncValidatorDebounceTime = const Duration(milliseconds: 500),
>     Suggestions<WifiData?>? suggestions,
>     ExtraData? extraData,
>   }) : super(
>     validators: validators,
>     asyncValidators: asyncValidators,
>     asyncValidatorDebounceTime: asyncValidatorDebounceTime,
>     initialState: WifiSetupBlocState(
>       isValueChanged: false,
>       initialValue: initialValue,
>       updatedValue: initialValue,
>       value: initialValue,
>       error: FieldBlocUtils.getInitialStateError(
>         validators: validators,
>         value: initialValue,
>       ),
>       isDirty: false,
>       suggestions: suggestions,
>       isValidated: FieldBlocUtils.getInitialIsValidated(
>         FieldBlocUtils.getInitialStateIsValidating(
>           asyncValidators: asyncValidators,
>           validators: validators,
>           value: initialValue,
>         ),
>       ),
>       isValidating: FieldBlocUtils.getInitialStateIsValidating(
>         asyncValidators: asyncValidators,
>         validators: validators,
>         value: initialValue,
>       ),
>       name: FieldBlocUtils.generateName(name),
>       toJson: (value) => value,
>       extraData: extraData,
>     ),
>   );
> 
> }
> 
> /// A material design checkbox.
> class WifiSetupBlocBuilder extends StatelessWidget {
>   const WifiSetupBlocBuilder({
>     Key? key,
>     required this.wifiFieldBloc,
>     this.enableOnlyWhenFormBlocCanSubmit = false,
>     this.isEnabled = true,
>     this.errorBuilder,
>     this.padding,
>     this.nextFocusNode,
>     this.animateWhenCanShow = true,
>   }) : super(key: key);
> 
>   /// {@macro flutter_form_bloc.FieldBlocBuilder.fieldBloc}
>   final WifiSetupBloc<dynamic> wifiFieldBloc;
> 
>   /// {@macro flutter_form_bloc.FieldBlocBuilder.errorBuilder}
>   final FieldBlocErrorBuilder? errorBuilder;
> 
>   /// {@macro flutter_form_bloc.FieldBlocBuilder.enableOnlyWhenFormBlocCanSubmit}
>   final bool enableOnlyWhenFormBlocCanSubmit;
> 
>   /// {@macro flutter_form_bloc.FieldBlocBuilder.isEnabled}
>   final bool isEnabled;
> 
>   /// {@macro flutter_form_bloc.FieldBlocBuilder.padding}
>   final EdgeInsetsGeometry? padding;
> 
>   /// {@macro flutter_form_bloc.FieldBlocBuilder.nextFocusNode}
>   final FocusNode? nextFocusNode;
> 
>   /// {@macro  flutter_form_bloc.FieldBlocBuilder.animateWhenCanShow}
>   final bool animateWhenCanShow;
> 
>   @override
>   Widget build(BuildContext context) {
>     return CanShowFieldBlocBuilder(
>       fieldBloc: wifiFieldBloc,
>       animate: animateWhenCanShow,
>       builder: (_, __) {
>         return BlocBuilder<WifiSetupBloc, WifiSetupBlocState>(
>           bloc: wifiFieldBloc,
>           builder: (context, state) {
>             final isEnabled = fieldBlocIsEnabled(
>               isEnabled: this.isEnabled,
>               enableOnlyWhenFormBlocCanSubmit:
>               enableOnlyWhenFormBlocCanSubmit,
>               fieldBlocState: state,
>             );
> 
>             return DefaultFieldBlocBuilderPadding(
>               padding: padding,
>               child: _buildWidget(context, isEnabled, state),
>             );
>           },
>         );
>       },
>     );
>   }
> 
>   Widget _buildWidget(BuildContext context, bool isEnabled, WifiSetupBlocState state) {
>     return OutlinedButton(
>       onPressed: isEnabled ? () {
>         showDialog(
>           context: context,
>           builder: (wlancontext) {
>             return AlertDialog(
>               title: const Text("WLAN"),
>               content: WillPopScope(
>                   child: SingleChildScrollView(
>                     child: SizedBox(
>                       width: double.maxFinite,
>                       child: WifiList(
>                         onConnected: (wifi) {
>                           showDialog(
>                             context: wlancontext,
>                             builder: (passwordcontext) {
>                               return WillPopScope(
>                                   child: PasswordDialog(
>                                     title: wifi.wifiName,
>                                     accept: "Bestätigen",
>                                     abort: "Abbrechen",
>                                     onAccept: (pw) {
>                                       WiFiForIoTPlugin.getSSID()
>                                           .then((value) {
>                                         wifi
>                                             .connect(pw)
>                                             .then((value) {
>                                           if (value) {
>                                             Navigator.of(wlancontext)
>                                                 .pop();
>                                             Navigator.of(
>                                                 passwordcontext)
>                                                 .pop();
>                                             var onChange = fieldBlocBuilderOnChange<WifiData?>(
>                                               isEnabled: isEnabled,
>                                               nextFocusNode: nextFocusNode,
>                                               onChanged: wifiFieldBloc.changeValue,
>                                             );
>                                             if(onChange != null) onChange(WifiData(wifi, pw));
>                                           } else {
>                                             ScaffoldMessenger.of(
>                                                 context)
>                                                 .showSnackBar(
>                                                 const SnackBar(
>                                                     content: Text(
>                                                         "WLAN konnte nicht verbunden werden")));
>                                           }
>                                         });
>                                       });
>                                     },
>                                     onAbort: () {
>                                       Navigator.of(passwordcontext)
>                                           .pop();
>                                     },
>                                   ),
>                                   onWillPop: () async => false);
>                             },
>                             barrierDismissible: false,
>                           );
>                         },
>                       ),
>                     ),
>                   ),
>                   onWillPop: () async => false),
>               actions: [
>                 OutlinedButton(
>                     onPressed: () {
>                       Navigator.of(wlancontext).pop();
>                     },
>                     child: const Text("Abbrechen")),
>               ],
>             );
>           },
>           barrierDismissible: false,
>         );
>       } : null,
>       child: state.value == null
>           ? const Text("Einrichten")
>           : Text(state.value!.wifi.wifiName),
>     );
>   }
> }
> ```

**Comment by aaassseee** [comment]
With reading the code it seems that you are trying to build a WIFI selection right? I think I am missing something, could you elaborate more?

**Comment by 538023** [comment]
@aaassseee So currently it is important what is in _buildWidget. If there is another possibility to build it differently I like to use it :). Promlematic is only that I generally have little time and can not wait for a merge. Uni project delivery is tomorrow and fix today the one or other bug still.

**Comment by aaassseee** [comment]
Sure you can use you own fork if you are in hurry :). Feel free to give more info after your delivery. I think this post may help you [#288](https://github.com/GiancarloCode/form_bloc/issues/180#issuecomment-1147395977) you can have a quick look if you are free.

**Comment by aaassseee** [comment]
We can discuss tomorrow if you too busy with your project delivery.

**Comment by 538023** [comment]
@aaassseee you said it is possible without using my pullrequest with a raw Bloc Builder. But because i need custom data (Wifidata) how can provide it.
And no. My project delivery is tomorrow yes. But i need it for tomorrow so, its important to find a solution for this today.

**Comment by aaassseee** [comment]
@538023 Well then is there a reason to use WifiSetupBloc instead of a InputFieldBloc?

**Comment by 538023** [comment]
@aaassseee 

Okay, I didn't know that either.
Okay I have changed it now:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_form_bloc/flutter_form_bloc.dart';
import 'package:wifi_iot/wifi_iot.dart';

import 'wifi.dart';
import 'wifi_list.dart';
import 'password_dialog.dart';

class WifiData {
  Wifi wifi;
  String password;

  WifiData(this.wifi, this.password);
}

ValueChanged<T>? fieldBlocBuilderOnChange<T>({
  required bool isEnabled,
  bool readOnly = false,
  required FocusNode? nextFocusNode,
  required void Function(T value) onChanged,
}) {
  if (isEnabled) {
    return (T value) {
      if (readOnly) return;
      onChanged(value);
      if (nextFocusNode != null) {
        nextFocusNode.requestFocus();
      }
    };
  }
  return null;
}

class WifiSetupBlocBuilder extends BlocBuilder<InputFieldBloc<WifiData?, void>,
    InputFieldBlocState<WifiData?, void>> {
  final InputFieldBloc<WifiData?, void> inputFieldBloc;
  final FieldBlocErrorBuilder? errorBuilder;
  final bool enableOnlyWhenFormBlocCanSubmit;
  final bool isEnabled;
  final EdgeInsetsGeometry? padding;
  final FocusNode? nextFocusNode;
  final bool animateWhenCanShow;

  WifiSetupBlocBuilder({
    Key? key,
    required this.inputFieldBloc,
    this.enableOnlyWhenFormBlocCanSubmit = false,
    this.isEnabled = true,
    this.errorBuilder,
    this.padding,
    this.nextFocusNode,
    this.animateWhenCanShow = true,
  }) : super(
            key: key,
            builder: (context, state) {
              return OutlinedButton(
                onPressed: isEnabled
                    ? () {
                        showDialog(
                          context: context,
                          builder: (wlancontext) {
                            return AlertDialog(
                              title: const Text("WLAN"),
                              content: WillPopScope(
                                  child: SingleChildScrollView(
                                    child: SizedBox(
                                      width: double.maxFinite,
                                      child: WifiList(
                                        onConnected: (wifi) {
                                          showDialog(
                                            context: wlancontext,
                                            builder: (passwordcontext) {
                                              return WillPopScope(
                                                  child: PasswordDialog(
                                                    title: wifi.wifiName,
                                                    accept: "Bestätigen",
                                                    abort: "Abbrechen",
                                                    onAccept: (pw) {
                                                      WiFiForIoTPlugin.getSSID()
                                                          .then((value) {
                                                        wifi
                                                            .connect(pw)
                                                            .then((value) {
                                                          if (value) {
                                                            Navigator.of(
                                                                    wlancontext)
                                                                .pop();
                                                            Navigator.of(
                                                                    passwordcontext)
                                                                .pop();
                                                            var onChange =
                                                                fieldBlocBuilderOnChange<
                                                                    WifiData?>(
                                                              isEnabled:
                                                                  isEnabled,
                                                              nextFocusNode:
                                                                  nextFocusNode,
                                                              onChanged:
                                                                  inputFieldBloc
                                                                      .changeValue,
                                                            );
                                                            if (onChange !=
                                                                null) {
                                                              onChange(WifiData(
                                                                  wifi, pw));
                                                            }
                                                          } else {
                                                            ScaffoldMessenger
                                                                    .of(context)
                                                                .showSnackBar(
                                                                    const SnackBar(
                                                                        content:
                                                                            Text("WLAN konnte nicht verbunden werden")));
                                                          }
                                                        });
                                                      });
                                                    },
                                                    onAbort: () {
                                                      Navigator.of(
                                                              passwordcontext)
                                                          .pop();
                                                    },
                                                  ),
                                                  onWillPop: () async => false);
                                            },
                                            barrierDismissible: false,
                                          );
                                        },
                                      ),
                                    ),
                                  ),
                                  onWillPop: () async => false),
                              actions: [
                                OutlinedButton(
                                    onPressed: () {
                                      Navigator.of(wlancontext).pop();
                                    },
                                    child: const Text("Abbrechen")),
                              ],
                            );
                          },
                          barrierDismissible: false,
                        );
                      }
                    : null,
                child: state.value == null
                    ? const Text("Einrichten")
                    : Text(state.value!.wifi.wifiName),
              );
            });
}

```

But I'm still missing something.

![grafik](https://user-images.githubusercontent.com/83300538/178111111-da120bed-a011-4bbc-9ee7-f2472ece6d9d.png)

**Comment by aaassseee** [comment]
Did you add to your form? Or did you set you bloc to inputFieldBloc in layout?

**Comment by aaassseee** [comment]
This error means cannot find you input field bloc in you current layout stack.

**Comment by 538023** [comment]
@aaassseee 
```dart
class DeviceSetupFormBloc extends FormBloc<Tuple2<Wifi, Location>, String> {
  final wifi = InputFieldBloc<WifiData?, void>(
      validators: [FieldBlocValidators.required], initialValue: null);
  final street = TextFieldBloc(
      validators: [FieldBlocValidators.required, LocationValidators.street]);
  final houseNumber = TextFieldBloc(validators: [
    FieldBlocValidators.required,
    LocationValidators.houseNumber
  ]);
  final zipCode = TextFieldBloc(
      validators: [FieldBlocValidators.required, LocationValidators.zipCode]);

  DeviceSetupFormBloc() {
    addFieldBloc(step: 0, fieldBloc: BooleanFieldBloc());
    addFieldBloc(step: 1, fieldBloc: wifi);
    addFieldBlocs(step: 2, fieldBlocs: [street, houseNumber, zipCode]);
  }

  @override
  void onSubmitting() async {
    switch (state.currentStep) {
      case 1:
        break;
      case 2:
        try {
          List<Location> locations = await locationFromAddress(
              '${street.value} ${houseNumber.value}, ${zipCode.value}',
              localeIdentifier: 'de_DE');
          Location location = locations.first;
        } catch (error, exception) {
          street.addFieldError('Kein valide Addresse');
          houseNumber.addFieldError('Kein valide Addresse');
          zipCode.addFieldError('Kein valide Addresse');
          emitFailure();
          return;
        }
        break;
    }
    emitSuccess();
  }
}

class DeviceSetupForm extends StatefulWidget {
  const DeviceSetupForm({Key? key}) : super(key: key);

  @override
  State<DeviceSetupForm> createState() => _DeviceSetupFormState();
}

class _DeviceSetupFormState extends State<DeviceSetupForm> {
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => DeviceSetupFormBloc(),
      child: SafeArea(
        child: FormBlocListener<DeviceSetupFormBloc, Tuple2<Wifi, Location>,
            String>(
          onSubmitting: (context, state) => LoadingDialog.show(context),
          onSubmissionFailed: (context, state) => LoadingDialog.hide(context),
          onSuccess: (context, state) {
            LoadingDialog.hide(context);

            if (state.stepCompleted == state.lastStep) {
              // Todo
            }
          },
          onFailure: (context, state) {
            LoadingDialog.hide(context);
          },
          child: StepperFormBlocBuilder<DeviceSetupFormBloc>(
            formBloc: context.read(),
            type: StepperType.horizontal,
            physics: const ClampingScrollPhysics(),
            stepsBuilder: (formBloc) {
              return [
                _introStep(formBloc!),
                _wifiStep(formBloc),
                _locationStep(formBloc)
              ];
            },
          ),
        ),
      ),
    );
  }

  FormBlocStep _introStep(DeviceSetupFormBloc deviceSetupFormBloc) {
    return const FormBlocStep(title: Text('Setup'), content: Text('hmmm'));
  }

  FormBlocStep _wifiStep(DeviceSetupFormBloc deviceSetupFormBloc) {
    return FormBlocStep(
        title: const Text('Wlan'),
        content: WifiSetupBlocBuilder(
          inputFieldBloc: deviceSetupFormBloc.wifi,
          enableOnlyWhenFormBlocCanSubmit: true,
        ));
  }

  FormBlocStep _locationStep(DeviceSetupFormBloc deviceSetupFormBloc) {
    return FormBlocStep(
        title: const Text('Standort'),
        content: Column(
          children: [
            TextFieldBlocBuilder(
              textFieldBloc: deviceSetupFormBloc.street,
              keyboardType: TextInputType.streetAddress,
              enableOnlyWhenFormBlocCanSubmit: true,
              decoration: const InputDecoration(labelText: 'Straße'),
            ),
            TextFieldBlocBuilder(
              textFieldBloc: deviceSetupFormBloc.houseNumber,
              keyboardType: TextInputType.text,
              enableOnlyWhenFormBlocCanSubmit: true,
              decoration: const InputDecoration(labelText: 'Hausnummer'),
            ),
            TextFieldBlocBuilder(
              textFieldBloc: deviceSetupFormBloc.zipCode,
              keyboardType: TextInputType.number,
              enableOnlyWhenFormBlocCanSubmit: true,
              decoration: const InputDecoration(labelText: 'Postleitzahl'),
            ),
            TextField(
              controller: TextEditingController(text: "Deutschland"),
              decoration: const InputDecoration(
                labelText: "Land",
                hintText: "Land",
              ),
              readOnly: true,
              enabled: false,
            )
          ],
        ));
  }
}

class DeviceSetup extends StatelessWidget {
  const DeviceSetup({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text("Setup"),
        ),
        body: const DeviceSetupForm());
  }
}
```

**Comment by aaassseee** [comment]
I think this line having the problem
```dart
          child: StepperFormBlocBuilder<DeviceSetupFormBloc>(
            formBloc: context.read(),
```

it should be 
``` dart
          child: StepperFormBlocBuilder<DeviceSetupFormBloc>(
            formBloc: context.read<DeviceSetupFormBloc>(),
```

**Comment by 538023** [comment]
@aaassseee if i replace it with this it fails completely:

Before the change:

![grafik](https://user-images.githubusercontent.com/83300538/178111618-0c110889-b26a-49e6-9094-8b5448d86956.png)

After your change:

![grafik](https://user-images.githubusercontent.com/83300538/178111631-69b45546-fb04-46c8-9535-48507f8e9a5a.png)

So now all pages are craching.

**Comment by aaassseee** [comment]
Oh god, you are using the wrong context
try wrap a builder after bloc provider
```dart
BlocProvider(
      create: (context) => DeviceSetupFormBloc(),
      child: /// wrap here SafeArea(
```

**Comment by aaassseee** [comment]
for example
```dart
return BlocProvider(
      create: (context) => WizardFormBloc(),
      child: Builder(
        builder: (context) {
          return Theme(
```

**Comment by 538023** [comment]
@aaassseee now it works again. Buuut Not the second page (index 1):

![grafik](https://user-images.githubusercontent.com/83300538/178111909-c5579321-5803-43bd-918f-0235c636dc5a.png)

**Comment by 538023** [comment]
```dart
import 'package:flutter/material.dart';
import 'package:flutter_form_bloc/flutter_form_bloc.dart';
import 'package:geocoding/geocoding.dart';
import 'package:tuple/tuple.dart';

import 'loading_dialog.dart';
import 'location_validators.dart';
import 'wifi.dart';
import 'wifi_setup.dart';

class DeviceSetupFormBloc extends FormBloc<Tuple2<Wifi, Location>, String> {
  final wifi = InputFieldBloc<WifiData?, void>(
      validators: [FieldBlocValidators.required], initialValue: null);
  final street = TextFieldBloc(
      validators: [FieldBlocValidators.required, LocationValidators.street]);
  final houseNumber = TextFieldBloc(validators: [
    FieldBlocValidators.required,
    LocationValidators.houseNumber
  ]);
  final zipCode = TextFieldBloc(
      validators: [FieldBlocValidators.required, LocationValidators.zipCode]);

  DeviceSetupFormBloc() {
    addFieldBloc(step: 0, fieldBloc: BooleanFieldBloc());
    addFieldBloc(step: 1, fieldBloc: wifi);
    addFieldBlocs(step: 2, fieldBlocs: [street, houseNumber, zipCode]);
  }

  @override
  void onSubmitting() async {
    switch (state.currentStep) {
      case 1:
        break;
      case 2:
        try {
          List<Location> locations = await locationFromAddress(
              '${street.value} ${houseNumber.value}, ${zipCode.value}',
              localeIdentifier: 'de_DE');
          Location location = locations.first;
        } catch (error, exception) {
          street.addFieldError('Kein valide Addresse');
          houseNumber.addFieldError('Kein valide Addresse');
          zipCode.addFieldError('Kein valide Addresse');
          emitFailure();
          return;
        }
        break;
    }
    emitSuccess();
  }
}

class DeviceSetupForm extends StatefulWidget {
  const DeviceSetupForm({Key? key}) : super(key: key);

  @override
  State<DeviceSetupForm> createState() => _DeviceSetupFormState();
}

class _DeviceSetupFormState extends State<DeviceSetupForm> {
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => DeviceSetupFormBloc(),
      child: Builder(builder: (context) {
        return SafeArea(
          child: FormBlocListener<DeviceSetupFormBloc, Tuple2<Wifi, Location>,
              String>(
            onSubmitting: (context, state) => LoadingDialog.show(context),
            onSubmissionFailed: (context, state) => LoadingDialog.hide(context),
            onSuccess: (context, state) {
              LoadingDialog.hide(context);

              if (state.stepCompleted == state.lastStep) {
                // Todo
              }
            },
            onFailure: (context, state) {
              LoadingDialog.hide(context);
            },
            child: StepperFormBlocBuilder<DeviceSetupFormBloc>(
              formBloc: context.read<DeviceSetupFormBloc>(),
              type: StepperType.horizontal,
              physics: const ClampingScrollPhysics(),
              stepsBuilder: (formBloc) {
                return [
                  _introStep(formBloc!),
                  _wifiStep(formBloc),
                  _locationStep(formBloc)
                ];
              },
            ),
          ),
        );
      },)
    );
  }

  FormBlocStep _introStep(DeviceSetupFormBloc deviceSetupFormBloc) {
    return const FormBlocStep(title: Text('Setup'), content: Text('hmmm'));
  }

  FormBlocStep _wifiStep(DeviceSetupFormBloc deviceSetupFormBloc) {
    return FormBlocStep(
        title: const Text('Wlan'),
        content: WifiSetupBlocBuilder(
          inputFieldBloc: deviceSetupFormBloc.wifi,
          enableOnlyWhenFormBlocCanSubmit: true,
        ));
  }

  FormBlocStep _locationStep(DeviceSetupFormBloc deviceSetupFormBloc) {
    return FormBlocStep(
        title: const Text('Standort'),
        content: Column(
          children: [
            TextFieldBlocBuilder(
              textFieldBloc: deviceSetupFormBloc.street,
              keyboardType: TextInputType.streetAddress,
              enableOnlyWhenFormBlocCanSubmit: true,
              decoration: const InputDecoration(labelText: 'Straße'),
            ),
            TextFieldBlocBuilder(
              textFieldBloc: deviceSetupFormBloc.houseNumber,
              keyboardType: TextInputType.text,
              enableOnlyWhenFormBlocCanSubmit: true,
              decoration: const InputDecoration(labelText: 'Hausnummer'),
            ),
            TextFieldBlocBuilder(
              textFieldBloc: deviceSetupFormBloc.zipCode,
              keyboardType: TextInputType.number,
              enableOnlyWhenFormBlocCanSubmit: true,
              decoration: const InputDecoration(labelText: 'Postleitzahl'),
            ),
            TextField(
              controller: TextEditingController(text: "Deutschland"),
              decoration: const InputDecoration(
                labelText: "Land",
                hintText: "Land",
              ),
              readOnly: true,
              enabled: false,
            )
          ],
        ));
  }
}

class DeviceSetup extends StatelessWidget {
  const DeviceSetup({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text("Setup"),
        ),
        body: const DeviceSetupForm());
  }
}
```

**Comment by aaassseee** [comment]
is the error show when pressing the button?

**Comment by aaassseee** [comment]
WifiSetupBlocBuilder super missing bloc: inputFieldBloc.
it should be
```dart
WifiSetupBlocBuilder({
    Key? key,
    required this.inputFieldBloc,
    this.enableOnlyWhenFormBlocCanSubmit = false,
    this.isEnabled = true,
    this.errorBuilder,
    this.padding,
    this.nextFocusNode,
    this.animateWhenCanShow = true,
  }) : super(
      key: key,
      bloc: inputFieldBloc,
```

**Comment by 538023** [comment]
@aaassseee there it is! I didn't even think of that! Thank you thank you! :D

**Comment by aaassseee** [comment]
If you having error when pressing the button try wrap another bloc provider.value in builder

e.g.
```dart
showDialog(
                          context: context,
                          builder: (wlancontext) {
                            return BlocProvide.value(
                              create: (context) => inputFieldBloc,
                              child: Builder(
                                builder: (context) {
                                  return AlertDialog(
```

**Comment by aaassseee** [comment]
Is that work without warping another BlocProvide.value on showDialog?

**Comment by 538023** [comment]
for me it works @aaassseee  Should it not work?

**Comment by aaassseee** [comment]
Because the code is not runnable on my side. If you trying to use bloc in showDialog it shouldn't get the bloc because bloc provider cannot provide bloc cross page and showDialog is actually another page in widget tree. so if you are using context.read, builder or listener it should not work. But it seems you didn't use those feature, so you are fine.

**Comment by 538023** [comment]
@aaassseee okay :) thanks again. Can i ask you a last question? How can i receive my data in

```data
if (state.stepCompleted == state.lastStep) {

}
```

**Comment by aaassseee** [comment]
You need to add object to 
```dart
emitSuccess(successResponse: data);
```

and receive data with
```dart
onSuccess: (context, state) {
  LoadingDialog.hide(context);
  state.successResponse
```

**Comment by 538023** [comment]
@aaassseee thanks :D and now really the last question: can i chnage the buttons?
I need to move continue to the right and the cancel to the left, also i need to change the text to: Weiter, Abbrechen
