### ISSUE TITLE
Change/customize DateTimeFieldBlocBuilder() view

### ISSUE THREAD

**Issue by nameaisy** [GiancarloCode/form_bloc#319]
i want to change the date picker UI inside DateTimeFieldBlocBuilder(), but i don't find how 

**FROM THIS:**
![Screenshot_2022-08-31-11-20-16-31_4efebcf25ca383b8d4037d7f6f34ce1b](https://user-images.githubusercontent.com/58661428/187592331-a399263c-72d7-469e-a027-1bf20f0325a9.jpg)

**TO THIS:**
![SCREENSHOTCUPERTINO](https://user-images.githubusercontent.com/58661428/187592129-d81266af-ad91-4fb5-adb1-95808295a9cd.png)

**Comment by aaassseee** [comment]
Hi @nameaisy, you can customize date picker by using bloc builder with input field bloc. You can check the example below
```dart
BlocBuilder<InputFieldBloc<DateTime, dynamic>,
    InputFieldBlocState<DateTime, dynamic>>(
  bloc: inputFieldBloc,
  builder: (context, state) {
    return CalendarDatePicker(
      initialDate: DateTime.now(),
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(Duration(days: 3)),
      currentDate: DateTime.now(),
      onDateChanged: (DateTime dateTime) {
        inputFieldBloc.updateValue(dateTime);
      },
    );
  },
),
```

**Comment by nameaisy** [comment]
Hello, thank you for your helpful answer @aaassseee
