### ISSUE TITLE
Add String to TextField when DropdownMenuItem changes

### ISSUE THREAD

**Issue by theFreeman96** [GiancarloCode/form_bloc#324]
Hi, I'm trying to make a form where the users can write down some lyrics.
My goal is to add a String to the TextField based on whatever option I choose in a DropdownButton widget.
How can I make the code work?

This is my onChanged in the DropdownMenuItem.
Note that I'm new to programming and there may be something off with this code:

                onChanged: (value) {
                  setState(() {
                    typeHint = value!;
                    if (typeHint == 'Verse') {
                      widget.verseField.newText = '<li>${widget.verseField.newText}';
                    } else if (typeHint == 'Chorus') {
                      widget.verseField.newText = '<i><b>Coro:</b>${widget.verseField.newText}</i><br>';
                    } else if (typeHint == 'Bridge') {
                      widget.verseField.newText = '<i><b>Bridge:</b>${widget.verseField.newText}</i><br>';
                    } else if (typeHint == 'Finale') {
                      widget.verseField.newText = '<i><b>Finale:</b>${widget.verseField.newText}</i><br>';
                    } else {
                      widget.verseField.newText = widget.verseField.newText;
                    }
                    log(value);
                  });
                },

And this is the TextField that I want to update, this is from your fantastic package:
              
          TextFieldBlocBuilder(
            textFieldBloc: widget.verseField.newText, // This is the text I want to update
            textCapitalization: TextCapitalization.sentences,
            keyboardType: TextInputType.multiline,
            minLines: 2,
            maxLines: 10,
            decoration: const InputDecoration(
              labelText: 'Text',
              prefixIcon: Icon(
                Icons.notes,
                color: kLightGrey,
              ),
            ),
            suffixButton: SuffixButton.clearText,
            clearTextIcon: const Icon(
              Icons.cancel,
              color: kLightGrey,
            ),
          ),

When trying to get this code to work I'm getting the following error:

> A value of type 'String' can't be assigned to a variable of type 'TextFieldBloc<dynamic>'.

Have you got any suggestions?
Maybe I'm trying to update the wrong code?

**Comment by aaassseee** [comment]
@theFreeman96 If you need to update the value of textfieldbloc call you need to call updateValue function. E.g. 
```dart
widget.verseField.newText.updateValue('<li>${widget.verseField.newText}')
```

**Comment by theFreeman96** [comment]
> @theFreeman96 If you need to update the value of textfieldbloc call you need to call updateValue function. E.g.
> 
> ```dart
> widget.verseField.newText.updateValue('<li>${widget.verseField.newText}')
> ```

This is working like a charm! Thanks a lot!!
