### ISSUE TITLE
conflict with flutter_localizations on flutter 3.22 (latest from may 2024)

### ISSUE THREAD

**Issue by mahirandigital** [GiancarloCode/form_bloc#347]
Because no versions of flutter_form_bloc match >0.31.0 <0.32.0 and flutter_form_bloc 0.31.0 depends on intl ^0.18.0, flutter_form_bloc ^0.31.0 requires intl ^0.18.0.
And because every version of flutter_localizations from sdk depends on intl 0.19.0, flutter_form_bloc ^0.31.0 is incompatible with flutter_localizations from sdk.
So, because mts depends on both flutter_localizations from sdk and flutter_form_bloc ^0.31.0, version solving failed.

**Comment by vasilich6107** [comment]
https://github.com/GiancarloCode/form_bloc/pull/312#issuecomment-1164240179

**Comment by mahirandigital** [comment]
thank you so much i didnt know this is exist
