### ISSUE TITLE
[Feature request] Add extraData / description property to SingleFieldBloc

### ISSUE THREAD

**Issue by GiancarloCode** [GiancarloCode/form_bloc#37]
<details>
<summary>What is SingleFieldBloc?</summary>
  <li>InputFieldBloc<Value>
  <li> TextFieldBloc 
  <li> BooleanFieldBloc 
  <li> SelectFieldBloc<Value>
  <li> MultiSelectFieldBloc<Value> 
</details>
In some cases, you may want to create dynamic fields based on json / object which you need to get from network request, so regarding user interface, you can't define a label name, image of background, etc.

You may also want more information on that field when you want to submit the form.

It would be useful to add a property that allows adding additional data to the `SingleFieldBloc`, that will be available in its state.

___

In the BLoC:
```dart
addFieldBloc(
     TextFieldBloc(
        name: 'item',
        extraData: {
          'id': itemResponse.label,
          'group': itemResponse.group,
          'label': itemResponse.label,
        }
      ),
  path: 'list',
)
```
In the UI:
```dart
           FieldBlocListBuilder(
              fieldBlocList: state.fieldBlocFromPath('list'),
              itemBuilder: (context, fieldBlocList, index) {
                final textFieldBloc= fieldBlocList[index].asTextFieldBloc;
                return TextFieldBlocBuilder(
                  textFieldBloc: textFieldBloc,
                  decoration: InputDecoration(
                    labelText: textFieldBloc.state.extraData['label'],
                  ),
                );
              },
            ),
```
___

### Option 1:
```dart
dynamic extraData
```
Any type... so you need to cast fo static analysis
example:
```dart
(textFieldBloc.state.extraData as CustomType).label;
(textFieldBloc.state.extraData as Map<String, dynamic>)['label'];
```
### Option 2:
```dart
Map<String, dynamic> extraData
```
Like a json
example:
```dart
textFieldBloc.state.extraData['label']
```
###  Option 3:
```dart
CustomType extraData...
```
To have static analysis we should add an extra type to the singleFieldBlocs, something that can be annoying.
for example:
```dart
InputFieldBloc<Value, ExtraData>
TextFieldBloc<ExtraData>
```

___
### Option 1:
```dart
extraData
```
### Option 2:
```dart
description
```
### Do you suggest another name? which one?

___

**Comment by GiancarloCode** [comment]
@Reprevise what do you think?

**Comment by Reprevise** [comment]
I think it's a good idea. I don't really like the whole dynamic map situation so I prefer option 3. For the name, I think extraData is a better name as description sounds like "this text field is where you enter your name" type of description.

**Comment by GiancarloCode** [comment]
If I think I will go for the third option, although it adds a bit of boilerplate, it will give us a lot of flexibility with static analysis.

**Comment by Reprevise** [comment]
Yeah, I don't like dynamic maps as it's really a guessing game and it's hard to know whether you're typing the right key name. I like the IntelliSense that comes from a class.

**Comment by GiancarloCode** [comment]
🔥 Added in form bloc v0.11.0 🔥
