### ISSUE TITLE
OnTap is not working

### ISSUE THREAD

**Issue by rodriger06** [GiancarloCode/form_bloc#4]
great package to use.  I find it very helpful. however, I noticed that onTap functionality doesnt work on TextFieldBlocBuilder.  when the text field is click/tap, the code inside onTap  doesnt execute.  please solve this issue.  your package is excellent but without OnTap functionally working it becomes limited to some people

**Comment by GiancarloCode** [comment]
@rodriger06 Thank you, solved in flutter_form_bloc 0.6.0 🎉
