### ISSUE TITLE
Using datepicker or year picker

### ISSUE THREAD

**Issue by jawadsahil** [GiancarloCode/form_bloc#40]
Are we limited to use only textbox , dropdown , checkbox and radio? 
    
    https://github.com/GiancarloCode/form_bloc/tree/master/packages/flutter_form_bloc#widgets

I need to have a text box with which should only allow the user to select year between 1970 to 2020 (or current year). Populating the dropdown with all years does not look good.

**Comment by GiancarloCode** [comment]
Hello, you can use any type of widget, it is pretty easy. 😁

The idea is that you have defined all the rules of your form, and you can use any widget easily without any problem.

For example for a date time picker

pubspec,yaml
```yalm
  intl: ^0.16.0
  datetime_picker_formfield: ^1.0.0
```
```dart
import 'package:datetime_picker_formfield/datetime_picker_formfield.dart';
import 'package:flutter/material.dart';
import 'package:flutter_form_bloc/flutter_form_bloc.dart';
import 'package:intl/intl.dart';

class DateTimeFieldBlocBuilder extends StatefulWidget {
  DateTimeFieldBlocBuilder({
    Key key,
    @required this.dateTimeFieldBloc,
    @required this.labelText,
  }) : super(key: key);

  final InputFieldBloc<DateTime> dateTimeFieldBloc;
  final String labelText;

  @override
  _DateTimeFieldBlocBuilderState createState() =>
      _DateTimeFieldBlocBuilderState();
}

class _DateTimeFieldBlocBuilderState extends State<DateTimeFieldBlocBuilder> {
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: BlocBuilder<InputFieldBloc, InputFieldBlocState>(
        bloc: widget.dateTimeFieldBloc,
        builder: (context, state) {
          return DateTimeField(
            format: DateFormat("dd-MM-yyyy"),
            initialValue: state.value,
            resetIcon: null,
            onChanged: (value) {
              widget.dateTimeFieldBloc.updateValue(value);
            },
            onShowPicker: (context, currentValue) {
              return showDatePicker(
                  context: context,
                  firstDate: DateTime(1970),
                  initialDate: currentValue ?? DateTime.now(),
                  lastDate: DateTime(2020));
            },
            decoration: InputDecoration(
              labelText: widget.labelText,
              prefixIcon: Icon(Icons.calendar_today),
              border: OutlineInputBorder(),
              errorText: state.canShowError
                  ? state.error /* map errors to localized message */ : null,
            ),
          );
        },
      ),
    );
  }
}

```

P.D. Today or tomorrow we will have a new version with some breaking changes, but it will be to make it easier to use and allow support for wizards / steps form :D

**Comment by jawadsahil** [comment]
> P.D. Today or tomorrow we will have a new version with some breaking changes, but it will be to make it easier to use and allow support for wizards / steps form :D

Hoping for the best :) I will try to update to new version and fix the code if something breaks. BTW I love the quick response from you. Do you ever sleep? :)  🥇

**Comment by GiancarloCode** [comment]
Haha, just you write at the right time :)

**Comment by vasilich6107** [comment]
You'll also need to add 
```
 if (dateTimeFieldBloc == null) {
      return Container();
    }

```

as a first line after `build` method

**Comment by GiancarloCode** [comment]
Thanks, everything is already implemented, I am finishing the last tutorial and I publish the new version in about 1 hour
