### ISSUE TITLE
how can i  select  date and save as string by this package?

### ISSUE THREAD

**Issue by hasanm08** [GiancarloCode/form_bloc#42]

**Comment by vasilich6107** [comment]
May be #40 could help you?

**Comment by GiancarloCode** [comment]
@vasilich6107 thanks that is right.
@hasanm08, Sorry not to answer, today I will publish a new version with many improvements and it will also include widgets for the time and date.

**Comment by vasilich6107** [comment]
Fantastic!

**Comment by GiancarloCode** [comment]
Now you can use `DateTimeFieldBlocBuilder` or `TimeFieldBlocBuilder`.
New release v0.11.0 🔥
Checkout the tutorials:
https://giancarlocode.github.io/form_bloc/
