### ISSUE TITLE
Optional field but validation converts it to required

### ISSUE THREAD

**Issue by BreX900** [GiancarloCode/form_bloc#44]
I can't create an optional and validated field
For example, I want the user to enter an email but optionally.
For this I write the following:
```dart
addFieldBloc(fieldBloc: TextFieldBloc(name: 'email', validator: [FieldBlocValidators.email]))
```
But this is the verification code of the email:
```dart
static String email(String string) {
    final emailRegExp = RegExp(
      r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$",
    );
    if (string != null && emailRegExp.hasMatch(string)) {
      return null;
    }
    return FieldBlocValidatorsErrors.email;
  }
```
If `string` is null or empty it will return an error. So the field is 'required' but that's not what I want to achieve
So the correct code would be:
```dart
static String email(String string) {
    final emailRegExp = RegExp(
      r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$",
    );
    if (string == null || string.isEmpy || emailRegExp.hasMatch(string)) {
      return null;
    }
    return FieldBlocValidatorsErrors.email;
  }
```
PS: In the case instead I want the field to be an email and that it is required I will write then
```dart
addFieldBloc(fieldBloc: TextFieldBloc(name: 'email', validator: [
  FieldBlocValidators.requiredText,  
  FieldBlocValidators.email,
]))
```
This would create problems if the `email` is before` requiredText` but it can be solved by adding `isRequired` as always proposed in the first position of the list
What do you think about it? Thanks

**Comment by GiancarloCode** [comment]
@BreX900 Haha I created this issue today https://github.com/GiancarloCode/form_bloc/issues/43,
I have implemented it in the new version that will also support forms with fields,
It will be published today or tomorrow.

if you have any suggestion please make it :)

**Comment by BreX900** [comment]
Yes. But the problem here is in the `FieldBlocValidators`. which impose a field as 'required' even if it is 'optional'
But if you say you have solved the new version then I close the Issus

**Comment by GiancarloCode** [comment]
You mean this?

>  `isRequired` by default is false, and add FieldBlocValidatorsErrors.required like error message.

>  Also with this change, we can have fields that can have different validators, but that does not imply that it is required, **so they will never be invoked if the field is empty and isRequired is false**

**Comment by BreX900** [comment]
yes, I didn't notice this part:
`but that does not imply that it is required`
They looked forward to the update then, thank you very much <3

**Comment by GiancarloCode** [comment]
@BreX900 could you write me on discord?
GiancarloCode#4227
