### ISSUE TITLE
Unexpected contentPadding for DateTimeFieldBloc

### ISSUE THREAD

**Issue by vasilich6107** [GiancarloCode/form_bloc#48]
Hi. Thanks again for 0.11.0 update.

I tried to use the `DateTimeFieldBloc` but I've found some unexpected behaviour.

```
if (decoration.contentPadding == null) {
      decoration = decoration.copyWith(
        contentPadding: decoration.border is OutlineInputBorder ||
                Theme.of(context).inputDecorationTheme.border
                    is OutlineInputBorder
            ? EdgeInsets.fromLTRB(12, 20, 0, 20)
            : EdgeInsets.fromLTRB(12, 12, 0, 12),
      );
    }
```

This caused datetime input to look a little bit bigger than the regular input. 
I dig through the textfield initial implementation and found that in dense decoration mode(isDense: true) the content padding slightly different

```
 if (decoration.filled == true) { // filled == null same as filled == false
        contentPadding = decorationContentPadding ?? (decorationIsDense
          ? const EdgeInsets.fromLTRB(12.0, 8.0, 12.0, 8.0)
          : const EdgeInsets.fromLTRB(12.0, 12.0, 12.0, 12.0));
```

This took me 20-30 minutes to adopt the `DaterTimeFieldBloc` for my needs.
Also this design choice makes the `DateTimeFieldBloc` to ignore `isDense` prop in decoration.

The same relates to the padding around both `DateTimeFieldBloc` and  `TextFieldBloc` which is slightly unexpected to have)

Do we actually need those design tweaks?
From my perspective the main goal of built in components is to carefully pass through the options without any modifications.

**Comment by GiancarloCode** [comment]
Thanks for reporting this.

Yes, it doesn't make sense :)

Fixed in flutter_form_bloc 0.11.1
