### ISSUE TITLE
Validators are not fired when field is empty.

### ISSUE THREAD

**Issue by vasilich6107** [GiancarloCode/form_bloc#49]
From 0.11.0 there is `isRequired` flag. 
But if I do not need the built in required validation? 
What if I want custom message for required case?

In case if I do not pass the `isRequired` the validators are not fired if the input value is empty.

The previous solution with validators array way clear and usable. The updated one is not so flexible...

Is there a possibility to revert error handling to previous version?

**Comment by GiancarloCode** [comment]
The general idea is to separate the user interface from the bloc, so you can think of errors as codes, in applications they are just a language the error could be the same message.

You can overwrite globally the current error messages and add localizations like this:
```dart
void main() {
  FieldBlocBuilder.defaultErrorBuilder = (context, error, fieldBloc) {
    switch (error) {
      case FieldBlocValidatorsErrors.required:
        // return tr('my_field_required_error';
        // return Localizations.of(context).nyFieldRequiredError;
        return 'This field is required.';
      default:
        return error;
    }
  };

  runApp(App());
}
```
And also each field bloc builder has the `errorBuilder` parameter, in case you want a specific message for only that field.
```dart
TextFieldBlocBuilder(
  textFieldBloc: formBloc.text1,
  errorBuilder: (context, error) {
    switch (error) {
      case FieldBlocValidatorsErrors.required:
        // return 'field_required'.trl();
        // return Localizations.of(context).fieldErrorLabel;
        return 'This field is required.';
      default:
        return error;
    }
  },
),
```
If you have any suggestion make it :)

**Comment by vasilich6107** [comment]
thanks for quick response

**Comment by GiancarloCode** [comment]
@vasilich6107  What do you think?

**Comment by vasilich6107** [comment]
Great. I even have a possibility to fire flushbar for case when the one line of error message is not enough

```
 errorBuilder: (context, error) {
                                          switch (error) {
                                            case FieldBlocValidatorsErrors
                                                .required:
                                              WidgetsBinding.instance
                                                  .addPostFrameCallback((_) {
                                                Flushbar(
                                                  title: "Hey Ninja",
                                                  message:
                                                      "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                                                  duration:
                                                      Duration(seconds: 3),
                                                )..show(context);
                                              });

                                              return 'This field is required.';
                                            default:
                                              return error;
                                          }
                                        },
```

**Comment by vasilich6107** [comment]
`But if I do not need the built in required validation?`

Here is an example.

I have a form with input field for value and comment field.
The value is required only if comment field is empty.
If user enters a comment describing the issues why he is not able to fill the value field it should not be required anymore. So here is an example of conditional `isRequired`.

I suppose that this case could not be implemented with current `in house` required validation.
May be I'm wrong...

**Comment by GiancarloCode** [comment]
Yes, currently not possible to make `isRequired` conditional.

Although your case seems more like a conditional field, check this example and tell me.

https://giancarlocode.github.io/form_bloc/#/conditional_fields_example

___


I just added a validation example based on another field, check it out as the approach I think we will take is similar.

https://giancarlocode.github.io/form_bloc/#/validation_based_on_other_field
(If you don't see the example open it incognito, I still have problems with the cache :( )

I can add a `validateWhen` function as parameter and also offer method to update this function.


* `validateWhen` : This function receives the current value of the field as a parameter, and must return true if you want validation ([isRequired], [validators] and [asyncValidators]) to be applied to that value, or false if you do not want validation to be applied to that value. By default this function returns `true` so all values ​​will be validated.


```dart
  final fieldBloc1 = InputFieldBloc<int, dynamic>(
    isRequired: true,
  );

  final fieldBloc2 = InputFieldBloc<int, dynamic>(
    name: 'field2',
    isRequired: true,
   // not work for your case, only for static members
   // but it is useful if you have validators that do not depend on other fields
    validateWhen: (value) => (value != 'some value'), 
  );
```
For your case 
```dart
  final field1 = InputFieldBloc(
    isRequired: true,
  );
  final field2 = TextFieldBloc(
    isRequired: true,
  );

  MyFormBloc() {
    addFieldBlocs(
      fieldBlocs: [field1, field2],
    );

    field2
      ..updateValidateWhen((value) => field1.value != null)
      ..subscribeToFieldBlocs([field1]);
  }

```


 ## Do you have any comments, I'm still not sure?

**Comment by vasilich6107** [comment]
I’ll look through your suggestions.
From my current perspective that removing the `isRequired` in favor of regular validator will solve all the cases.

Maybe you can explain why we need `isRequired` locked inside? I do not see any advantages.

**Comment by vasilich6107** [comment]
I looked through your suggestions.

> Although your case seems more like a conditional field, check this example and tell me.
It could be the case, but it is not a conditional fields. The both fields should be on the form at once - this is a business requirement. 

> I can add a validateWhen function as parameter and also offer method to update this function
This case is like overengineering. First we locked `isRequired` validation inside and now we are trying to overcome this with more complicated solution.

From what I see the `isRequired` flag is some kind of 'short path' for more quick form implementation.
But as you see from my example it brings only the limitation in case when form requires more flexible validation.

**Comment by vasilich6107** [comment]
We can try to do the next 

```
String _getError(Value value,
      {bool isInitialState = false, bool forceValidation = false}) {
    String error;

    if (forceValidation || _autoValidate) {
      if(_isRequired) {
        final isRequiredError = _isRequiredValidator(value);

        if (_isRequired) {
          error = isRequiredError;
        }
      }

      final hasError = error != null;
      final hasValidators = _validators != null;

      if (!hasError && hasValidators) {
        for (var validator in _validators) {
          error = validator(value);
          if (error != null) return error;
        }
      }
    } else if (!isInitialState) {
      error = state.error;
    }

    return error;
  }
```

**Comment by GiancarloCode** [comment]
(1)  It is less verbose in simple forms (Although this is not a strong reason but it is a plus haha)
```dart
  final name = TextFieldBloc(isRequired: true);
```
vs
```dart
  final name = TextFieldBloc(
     validators: [FieldBlocValidators.required],
  );
```

(2)  The main reason, is without this you will forced to add extra logic to your validators that is for fields that is not required.
Like this https://github.com/GiancarloCode/form_bloc/issues/44

The email validator need to check if the string isEmpty or null
```dart
static String emailValidator(String string) {
    final emailRegExp = RegExp(
      r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$",
    );
    if (string == null || string.isEmpy || emailRegExp.hasMatch(string)) {
      return null;
    }
    return FieldBlocValidatorsErrors.email;
  }
```
and you need to add the required validator

```dart
  final name = TextFieldBloc(
     validators: [
       FieldBlocValidators.required,
       emailValidator
    ],
  );
```
____

 Also I noticed that if we remove `isRequired` we can solve your problem exactly like the example of `validation based of other field`
__

## We could go back to the previous version, but the problem is that it forces to add more logic in the validators, what do you think?
Also @beBreX900 
__

**Comment by vasilich6107** [comment]
@GiancarloCode please check my suggestion
https://github.com/GiancarloCode/form_bloc/issues/49#issuecomment-605212238

**Comment by vasilich6107** [comment]
Previous solution stopped the validators execution in case if the field is null but I did not specified `isRequired: true` :-)

**Comment by GiancarloCode** [comment]
This is because when `isRequired` is not set, by default is `false`.

With your proposal it would do the same as before, since when `isRequired` is false and the value is null/empty, the validators will be called.

I think we could make it by default not false (null), and in this case it would have the behavior you expect, but it seems confusing.

**Comment by GiancarloCode** [comment]
Going back to the previous version would make more sense since the `FieldBlocValidators.required ` now applies to all field blocs types.

But I would like to offer something for the fields not required but with validators

**Comment by vasilich6107** [comment]
The true and false is enough.
It will work as it is sound. Without confusion

If I pass isRequired: true I guard the next array of validators from additional checking that the incoming value != null

If I not specified the isRequred flag I’m ok with nullability.

**Comment by GiancarloCode** [comment]
But with this we have the same problem https://github.com/GiancarloCode/form_bloc/issues/44

In this case `isRequired` is used only for add a `required` validator, the idea is to avoid adding additional logic in the other validators else that parameter can be eliminated since it does not contribute much

**Comment by vasilich6107** [comment]
> Going back to the previous version would make more sense since the `FieldBlocValidators.required ` now applies to all field blocs types.

I vote for this with both hands)
Flexible and obvious behaviour.

**Comment by GiancarloCode** [comment]
If it is a good idea and if it is more flexible, and your case is solved super easy.

but before I would like to find a solution to avoid adding that kind of logic in the other validators when they are not required
or that behavior is expected?
I still don't know hahaha
if you have ideas :)

**Comment by vasilich6107** [comment]
> or that behavior is expected?

I think yes. 

In JS world I didn't see any embedded validators inside form engines.
For example 
- `formik` forces in examples the usage of `yup` - standalone library for validation
- `final-form` also does not have any embedded validations

The validators that are shipped with `form_bloc` is a good start.  But the form itself should be unaware of any validation rules - just run the bunch passed from outside.

**Comment by GiancarloCode** [comment]
Interesting, tomorrow to review a little more and the most probable thing is that I will make the change.
thanks

**Comment by GiancarloCode** [comment]
@vasilich6107 
There is a simpler solution that can accomplish what we both want.
Add the ability to assign the isRequriedValidator.
```dart
  final field1 = InputFieldBloc(isRequired: true);
  final field2 = TextFieldBloc(isRequired: true);

  MyFormBloc() {
    addFieldBlocs(fieldBlocs: [field1, field2]);

    field2
      ..updateIsRequiredValidator((value) => field1.value == null ? 'required' : null)
      ..subscribeToFieldBlocs([field1]);
  }
```
 What do you think?

**Comment by vasilich6107** [comment]
I’m still 100% sure that there is no place for in house validation inside field bloc.

The way you propose to achieve the compromise result just adds another method, to fix the inflexible design. Now I can add all validators through either “validators” array and one through replacement method. 

I tried to convince you to revert to the previous solution. The last decision will be yours. Nevertheless I’ll use any solution that will implement.

**Comment by GiancarloCode** [comment]
@vasilich6107  Well I'm still not convinced due to my lack of experience in other frameworks:(

Could you show me an example of how you would create Validator but that it only activates when the value is not null / empty?

(without having to do it as explicitly as in the example)
```if (string == null || string.isEmpy || emailRegExp.hasMatch(string)) ```

Maybe there is some package that does the trick or we can create something that is helpful for these cases, with that I would be calm that this case is easy to solve :)

**Comment by vasilich6107** [comment]
I read through the #44 issue. It’s states that bundled email validator acts not how @BreX900 expected(wanted). This is not a signal of issue it is a signal that the validator doesn’t match to the particular needs and you need to write your own one.
This is a good example how bundled validators(that are not designed like multi tool) causes the unwanted issues.
They could be moved out form `form_bloc` In to examples this will message customers ‘hey, here is an example. In custom cases write your own validators’

The common case is - when you need validator that runs only if value is not null just write it. It is not some kind of a bad practice.

**Comment by vasilich6107** [comment]
Please check this lib for validators list
https://pub.dev/documentation/validators/latest/validators/validators-library.html

The isNull method could be helpful 
https://pub.dev/documentation/validators/latest/validators/isNull.html

**Comment by vasilich6107** [comment]
I can also suggest you to make a call with some kind of screen sharing so we can clarify all the things faster)

**Comment by BreX900** [comment]
In post #44 I described how validators should be changed to make them more flexible and this was my proposal. And it is the same solution that I propose now
```dart
static String requiredValue(dynamic value) {
  if (value != null) return null;
 return requiredError;
}
static String requiredText(String text) {
  if (text == null || text.trim().isNotEmpty) return null;
  return requiredError;
}
static String requiredEmail(String email) {
  final emailRegExp = RegExp(r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$");
    if (string == null || string.isEmpy || emailRegExp.hasMatch(string))  return null;
   return requiredError;
}
```
If the field is required you will write
```dart
validators: [
  Validators.requiredValue,
  Validators.requiredText,
  Validators.requiredEmail,
]
```
If the field is optional but request validation you will write
```dart
validators: [
  Validators.requiredEmail,
]
```
If the field is required only if it is not null the value you will write
```dart
validators: [
  Validators.requiredText,
  Validators.requiredEmail,
]
```

**Comment by vasilich6107** [comment]
Hi 👋@BreX900
Thanks for joining the conversation.

From your message I see that you also do not need the 'isRequired' flag.
The built in validators reorganisation could be in any form. This will not affect the users who write the custom one.

**Comment by GiancarloCode** [comment]
@BreX900 @vasilich6107 thanks

@vasilich6107 My discord is GiancarloCode#4227
___
Yes, we will remove `isRequired`, at night I will launch the minor version deprecating it and another one where it no longer exists (0.12.0)

And let's change the built-in  validators to be valid as long as the value is `null` or empty.

```dart
  static String email(String string) {
    final emailRegExp = RegExp(
      r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$',
    );
    if (string == null || string.isEmpty || emailRegExp.hasMatch(string)) {
      return null;
    }

    return FieldBlocValidatorsErrors.email;
  }
```
This way if we want a required field we simply add the required validator, and that's it :)

```dart
validators: [
  FieldBlocValidators.required,
  FieldBlocValidators.email,
]
```
___

Sounds good to me, and the idea of built-in validators is to be able to easily use it and serve as a basis for others to create their own, localization for built-in validators will be added in the future, so I had my doubts, but with this I am satisfied.

Any comment?

**Comment by GiancarloCode** [comment]
@vasilich6107
flutter_form_bloc v0.12.0 was published 🚀

**Comment by vasilich6107** [comment]
Thanks!

**Comment by ignaciolopez12** [comment]
> ```dart
>   FieldBlocBuilder.defaultErrorBuilder = (context, error, fieldBloc) {
>     switch (error) {
>       case FieldBlocValidatorsErrors.required:
>         // return tr('my_field_required_error';
>         // return Localizations.of(context).nyFieldRequiredError;
>         return 'This field is required.';
>       default:
>         return error;
>     }
>   };
> ```

Es la unica manera para poder cambiarlo al idioma que queramos?

Is it the only way we can change it to the language we want?

**Comment by GiancarloCode** [comment]
@ignaciolopez12 hello

You can also use the `errorBuilder` parameter in each widget.

But it is recommended to overwrite the default since it applies to all widgets.

Think of your validation errors as error codes defined in your business logic layer or domain layer, so they are agnostic respect L10n, and are translated into messages for the user(L10n) in the presentation layer.

If you have any suggestion make it :)

**Comment by ignaciolopez12** [comment]
> @ignaciolopez12 hello
> 
> You can also use the `errorBuilder` parameter in each widget.
> 
> But it is recommended to overwrite the default since it applies to all widgets.
> 
> Think of your validation errors as error codes defined in your business logic layer or domain layer, so they are agnostic respect L10n, and are translated into messages for the user(L10n) in the presentation layer.
> 
> If you have any suggestion make it :)

Thanks. I have problem with DateTimeFieldBlocBuilder.

I need to put it in my language (Spanish) Argentina

> return DateTimeFieldBlocBuilder(
>       dateTimeFieldBloc: signInBloc.fechaNacimiento,
>       format: DateFormat('dd-MM-yyyy'),
>       initialDate: DateTime.now(),
>       firstDate: DateTime(1900),
>       lastDate: DateTime(2199),
>       locale: Locale('es', 'AR'),
>       decoration: InputDecoration(
>         labelText: 'Fecha de Nacimiento',
>         prefixIcon: Icon(Icons.calendar_today),
>         helperText: 'Prueba'
>       )
>     );

> The method 'formatMediumDate' was called on null.
> Receiver: null

**Comment by ignaciolopez12** [comment]
> > @ignaciolopez12 hello
> > You can also use the `errorBuilder` parameter in each widget.
> > But it is recommended to overwrite the default since it applies to all widgets.
> > Think of your validation errors as error codes defined in your business logic layer or domain layer, so they are agnostic respect L10n, and are translated into messages for the user(L10n) in the presentation layer.
> > If you have any suggestion make it :)
> 
> Thanks. I have problem with DateTimeFieldBlocBuilder.
> 
> I need to put it in my language (Spanish) Argentina
> 
> > return DateTimeFieldBlocBuilder(
> > dateTimeFieldBloc: signInBloc.fechaNacimiento,
> > format: DateFormat('dd-MM-yyyy'),
> > initialDate: DateTime.now(),
> > firstDate: DateTime(1900),
> > lastDate: DateTime(2199),
> > locale: Locale('es', 'AR'),
> > decoration: InputDecoration(
> > labelText: 'Fecha de Nacimiento',
> > prefixIcon: Icon(Icons.calendar_today),
> > helperText: 'Prueba'
> > )
> > );
> 
> > The method 'formatMediumDate' was called on null.
> > Receiver: null


I could but a text appears above saying "Select date", and I need it to be in Spanish

![aaaa](https://user-images.githubusercontent.com/19846325/82509234-a5e63980-9add-11ea-87c3-bcd478b6f562.png)

**Comment by NestorDevs** [comment]
En el caso de el
 `final role = SelectFieldBloc(items: [
    'Client',
    'Owner'
  ], validators: [
    FieldBlocValidators.required,
  ]);`

no e dado con la forma de poder usar multi idioma porque uso `S.of(context).algunTitulo` y pues no deberia colocar el build context en el bloc ... en esa caso como haria alli @GiancarloCode ???
