### ISSUE TITLE
suggestion menu reappearing after selecting one of the suggesstions

### ISSUE THREAD

**Issue by rodriger06** [GiancarloCode/form_bloc#5]
I was testing the code from the github repository.  i tried the complex login screen.  when i click on the email textfield, a suggesstion dropdown comes up.  when i choose a value, the textfield populates but the dropdown menu comes up again.  after the second time selecting the same value, then the suggestion dropdown disappear.  see attachment of value selected and menu still appear instead of disappearing 

<img width="186" alt="menu_reappearing" src="https://user-images.githubusercontent.com/49496303/70866087-3cad3980-1f33-11ea-9a72-73dd6d905de2.PNG">

![Android-Emulator-Nexus_5X_API_26_5554-12_15_2019-12_17_12-PM](https://user-images.githubusercontent.com/49496303/70866244-5485bd00-1f35-11ea-8638-42468271cee9.gif)

**Comment by GiancarloCode** [comment]
@rodriger06 Hello, I have released a new version of flutter_form_bloc and I do not see this behavior, could you please confirm it.

Thank you 😁
