### ISSUE TITLE
DateTimeFieldBloc removes existing value in case of cancel press

### ISSUE THREAD

**Issue by vasilich6107** [GiancarloCode/form_bloc#51]
Hi - it's me again)

If I have prepopulated value in DateTimeFieldBloc -> open the date picker -> press Cancel -> resets prepopulated value to `null`

Here is why - the datepicel returns null in case of cancel and you put it directly into the field value
```
if (type == DateTimeFieldBlocBuilderBaseType.date) {
                          final date = await _showDatePicker(context);
                          dateTimeFieldBloc.updateValue(date as T);
                        }
```

**Comment by GiancarloCode** [comment]
I set this, because we also need the user to deselect the date

I can change it, but we must also add a way for the user to deselect the date.

Do you have any suggestion?

I think we could make the selection of the same date to be deselected, but I would have to modify the `DatePickerDialog` of Flutter and I would like to avoid that

**Comment by vasilich6107** [comment]
In `detepicker_form_filed` it is implemented via `resetIcon`

https://github.com/jifalops/datetime_picker_formfield/blob/master/lib/datetime_picker_formfield.dart#L83

**Comment by GiancarloCode** [comment]
Adding a button in decoration may work.
I still have doubts,
* should the delete icon be displayed by default?

* if the user wants to change the icon they could do it like that, it is enough? i don't know haha

```dart
DateTimeFieldBlocBuilder(
  // ...
  decoration: InputDecoration(
      suffixIcon: IconButton(
        icon: Icon(Icons.clear),
        onPressed: formBloc.date1.clear,
      )),
),
`` ''

**Comment by vasilich6107** [comment]
Sure - the delete icon should be displayed by default
You could add an `assert(decoration. suffixIcon  == null)` and add appropriate note in comments

**Comment by GiancarloCode** [comment]
I will add it by default true
added also this properties:
  * showClearIcon
  * clearIcon

And the user can set suffix in decoration, this would overwrite the current behavior and allow them to put in whatever they want.

any comments?

**Comment by vasilich6107** [comment]
LGTM

**Comment by GiancarloCode** [comment]
Added in flutter_form_bloc 0.11.2
