### ISSUE TITLE
Hi! How can we obscure text field bloc for password?

### ISSUE THREAD

**Issue by wajeehulhassanvii** [GiancarloCode/form_bloc#53]
I tried to do it but was not successful. Can you please send an example snippet? Thanks

**Comment by wajeehulhassanvii** [comment]
Found it, we have to set suffix button.

**Comment by GiancarloCode** [comment]
@wajeehulhassanvii This is a built-in show/hide password,

If you want a custom behavior you can create a stateful widget and do whatever you want in the `suffixIcon` and `obscureText` like this https://stackoverflow.com/a/54040162/11768068

**Comment by wajeehulhassanvii** [comment]
thanks @GiancarloCode , I appreciate it.
