### ISSUE TITLE
pass dynamic items for SelectFieldBloc from api

### ISSUE THREAD

**Issue by basnetjiten** [GiancarloCode/form_bloc#59]
Hi there, I just stuck into problems for passing the dynamic value for the items for SelectFieldBloc rather than providing static values

**Comment by GiancarloCode** [comment]
@basnetjiten 
Do you have any doubt? the method is `updateItems`

**Comment by basnetjiten** [comment]
Okay thanks. Do we have also image upload as a form bloc ?  I have a forms and a image upload section. How do I use form bloc in this scenerio ?

**Comment by GiancarloCode** [comment]
Checkout this https://github.com/GiancarloCode/form_bloc/issues/57#issuecomment-609565908
And also if your submission has progress check [this tutorial](https://giancarlocode.github.io/form_bloc/#/submission_progress_example)
