### ISSUE TITLE
DateTimeFieldBlocBuilder still shows 'clear' icon if disabled

### ISSUE THREAD

**Issue by vasilich6107** [GiancarloCode/form_bloc#60]
DateTimeFieldBlocBuilder still shows 'clear' icon if disabled

In case of

```
DateTimeFieldBlocBuilder(
  isEnabled: false,
  padding: const EdgeInsets.all(0),
  format: DateFormat("yyyy-MM-dd"),
  firstDate: DateTime(1970),
  lastDate: DateTime(2100),
  initialDate: DateTime.now(),
  decoration: InputDecoration(
    labelText: 'Date',
    helperText: ' ',
  ),
  dateTimeFieldBloc: formBloc.previousCreatedAt,
),
```

you will get https://tppr.me/ki2NZ

**Comment by vasilich6107** [comment]
Adding `showClearIcon: false` could be helpfull)

**Comment by GiancarloCode** [comment]
@vasilich6107 Hello,
The following week I will do a refactoring of the internal implementation and some changes, if you have any feature request or suggestion it is a good time to do it :)

**Comment by vasilich6107** [comment]
Thanks for notifying. I’ll prepare my thoughts and leave it here.

**Comment by vasilich6107** [comment]
First thing that I'd like to address is the individual field re-build.
Currently if I tap on checkbox everything under the `FormBlocListener` is being rebuilt.

Autovalidation true/false
This a good approach that validators are executed on each field change. This allows to track the form consistency at every moment. But the error display logic is not adjustable(correct if I'm wrong)
If I have an `autovalidate: true` and email field(`Simple example` from https://giancarlocode.github.io/). Just after I enter the first symbol the form notifies me that the field is badly formatted. But I'm not done yet :-) How the form knows that I'm wrong?) The other case is `autovalidate: false` - I do not see the errors until I press 'Submit' this is a little bit annoying(from users perspective). It could lead the case that user fills long form and sees the errors far later.

This could be improved with two things - introducing the field meta data, and display error hook(callback).

Example from `react-final-form`(pretty proven solution)

```
isErrorField = (meta: Meta): boolean =>
    !!(meta && ((meta.error && meta.touched) || (meta.submitError && meta.submitFailed)));
``` 

This function checks if field has errors, if it was touched before or has submit errors and submit was failed. Returns the `true/false` and this is a sign whether to display an error.

Here is a link to full list of `meta` data of the field
https://github.com/final-form/react-final-form/blob/master/src/types.js.flow#L32

How this will help.

If user hits the field for the first time the `meta.touched` is `false`.
So we do not disturb the user during possible errors while he entering value for the first time.
After he switches to another field `meta.touched` becomes `true` and only than we can show an error.
If user gets back to the editing the `meta.touched` already `true` and now we show the realtime error display based on the assumption that the previous value was correct and if user alters it we notify him immediately that there is an error.

The default error display logic could stay the same. But with this extended meta data and error display hook everyone can alter the logic on his own demands.
