### ISSUE TITLE
AddFeildBlocsBuilder vs AddFeildBlocs

### ISSUE THREAD

**Issue by angwandi** [GiancarloCode/form_bloc#61]
When using conditional fields, there is no way to add FeildBlocBuilder(which does not exist by the way but would be nice to be added.)

There is no way to add DropdownFieldBlocBuilder to addFeildBlocs. 
It would be nice to have the option to add something like DropdownFieldBloc which can then be added to addFieldBlocs for conditional use.

**Comment by GiancarloCode** [comment]
Hello, could you explain yourself a little better, I did not understand :(

Did you see [this](https://giancarlocode.github.io/form_bloc/#/conditional_fields_example) tutorial ?, in theory with `onValueChanges` you could do anything you want

**Comment by angwandi** [comment]
Sorry if I am not clear enough. 

I saw the tutorial but there is no way to hide and show a  DropdownFieldBlocBuilder.
One can only hide or show a TextFeildBloc like in the tutorial above. 

I would like to do the same thing, but I want to hide and show DropdownFieldBlocBuilder instead of simple TextFeildBloc.

**Comment by GiancarloCode** [comment]
You can do it, simply add/remove a `SelectFieldBloc`.
For now all widgets are automatically hidden and displayed when they `are/are not` in the form bloc

for example:

```dart
class ConditionalFieldsFormBloc extends FormBloc<String, String> {
 final showSecretField = BooleanFieldBloc(); 
 final secretSelectField = SelectFieldBloc(
    validators: [FieldBlocValidators.required],
    items: ['No', 'Yes'],
  );
 ...
    showSecretField.onValueChanges(
      onData: (previous, current) async* {
        if (current.value) {
          addFieldBlocs(fieldBlocs: [secretSelectField]);
        } else {
          removeFieldBlocs(fieldBlocs: [secretSelectField]);
        }
      },
    );
...
```
Although if there are many conditionals the logic increases, it is still simple :)

**Comment by angwandi** [comment]
Works like a charm, 

Thank you

**Comment by GiancarloCode** [comment]
Awesome :)
