### ISSUE TITLE
[Question] How to detect a dropdown value change?

### ISSUE THREAD

**Issue by mrverdant13** [GiancarloCode/form_bloc#62]
When using a single `SelectFieldBloc`, it feels unnecessary to use a `FormBloc`, so it could be useful just to use that `SelectFieldBloc` (since it is already a BLoC) and detect its value changes or assign them a callback.

**Comment by GiancarloCode** [comment]
It makes sense, at the moment each field bloc is heavily coupled to a form bloc, and this allows all widgets to have animations when they are added or removed from the form bloc without the need to do any extra steps :), and other features like avoid changing the values when the state of the form bloc is submitting.

 ####  These days I plan to refactor a bit, so if you have any suggestions you can make them :)

In the same way, all the field blocs have the `onValueChanges` method, which returns a stream subscription, which offers you the previous and current state, you can also assign debounce time, and use some methods before and after the debounce time.
https://pub.dev/documentation/form_bloc/latest/form_bloc/SingleFieldBloc/onValueChanges.html

Check this example for a simple usage:
https://giancarlocode.github.io/form_bloc/#/conditional_fields_example

**Comment by mrverdant13** [comment]
That stream subscription workaround is functional and it is enough for now.
Thanks for the quick response!
