### ISSUE TITLE
Add focusNode and nextFocusNode to DateTimeFieldBlocBuilder and TimeFieldBlocBuilder

### ISSUE THREAD

**Issue by Reprevise** [GiancarloCode/form_bloc#67]
I would like to know if there's a way to add the `focusNode` and `nextFocusNode` parameter to the `DateTimeFieldBlocBuilder` and `TimeFieldBlocBuilder`. I assume you left it out for a reason, but it would be nice to have a consistent flow so I could just tap the button on my keyboard to go to the next field without having to tap the field.

**Comment by GiancarloCode** [comment]
Hello is that I have only seen that pattern in the text fields, so I was waiting for someone requesting haha,
I'll add it the day after tomorrow :)
if you are eager, it is basically:
1. add a method to display the date picker.
2. add a focus node
3. add a listener to the focus node to call the date picker method
__

In this and next week I will do a refactoring to the core, so if you have any requested it is a good time for you to do it :)

**Comment by Reprevise** [comment]
I appreciate this but I do have some questions:

1. If a user was, say at a text field and they pressed the "Next" button on their keyboard to move to the next field, will the picker open automatically?
2. After a picker closes, will it automatically go to the next field?
3. As a followup to question two, if that next field is a date and/or time field, will the picker open automatically?

**Comment by GiancarloCode** [comment]
1. yes.
2. yes, only if you set nextFocusNode
3. yes
You can try and play with textField and dropdown, and tell me, it would be the same flow.

**Comment by GiancarloCode** [comment]
Added in `flutter_form_bloc: 0.13.0`
