### ISSUE TITLE
Dart Close Sinks Warning

### ISSUE THREAD

**Issue by Reprevise** [GiancarloCode/form_bloc#7]
Above every bloc field I create in my classes I have to keep putting `// ignore: close_sinks`. I know that it closes the fields automatically so I don't have to call the `close()` method myself but is there anything that I or you can do? I know it's just a warning and not an error but it's still annoying.

**Comment by GiancarloCode** [comment]
@Reprevise Hello, this also seems annoying to me 🙁 , this is a problem in the `bloc` package so it cannot be addressed directly in this package. 

I invite you to read this issue https://github.com/felangel/bloc/issues/587 where they give [temporary solutions](https://github.com/felangel/bloc/issues/587#issuecomment-545490800), and as soon as it is resolved in the `bloc` package will also be resolved in `form_bloc`.

I hope it helps and if you have any suggestions do not hesitate to make it.

**Comment by Reprevise** [comment]
Thanks for your help. I've just added that analysis file to the root directory of my project.
