### ISSUE TITLE
Another exception was thrown: setState() called after dispose(): _DropdownFieldBlocBuilderWebState<String>#b95bf(lifecycle state: defunct, not mounted)

### ISSUE THREAD

**Issue by cylyl** [GiancarloCode/form_bloc#78]
Another exception was thrown: setState() called after dispose(): _DropdownFieldBlocBuilderWebState<String>#b95bf(lifecycle state: defunct, not mounted)

**Comment by GiancarloCode** [comment]
can you tell me how to reproduce the error?
