### ISSUE TITLE
Error in DateTimeFieldBlocBuilder

### ISSUE THREAD

**Issue by joaquimorg** [GiancarloCode/form_bloc#79]
When I select a date
![image](https://user-images.githubusercontent.com/1682318/80869339-d2a1f080-8c97-11ea-9a82-0d0accc9128c.png)

the value of the month is "00"

![image](https://user-images.githubusercontent.com/1682318/80869372-fcf3ae00-8c97-11ea-8d61-4a44e676e37e.png)

**Comment by GiancarloCode** [comment]
Hello, It is an error in the format I used in the example, later I will fix it :).

Read more about date formats : https://pub.dev/documentation/intl/latest/intl/DateFormat-class.html

Change this
```dart
   format: DateFormat('dd-mm-yyyy')
```
To this:
```dart
   format: DateFormat('dd-MM-yyyy')
```
P.D.
* mm: minutes
* MM: month

**Comment by joaquimorg** [comment]
Many thanks.
