### ISSUE TITLE
sister list_bloc or table_bloc

### ISSUE THREAD

**Issue by ayushin** [GiancarloCode/form_bloc#8]
Hi! This is a very useful package saving lots of boilerplate.

I was thinking if something similar should be created for loading / managing list / table data ?

With load/reload, load more, loading, error, delete, filter and to be combined with the form_bloc for the create/update? 

This will give us the full crud.

Any ideas about this or any similar package I should know about before giving it a try?

**Comment by GiancarloCode** [comment]
Thanks.

For improve the CRUD operations with form_bloc I propose [this](https://github.com/GiancarloCode/form_bloc/issues/9), please check it.

Regarding list_bloc is a good idea, currently you can check https://pub.dev/packages/flutter_bloc_patterns It is similar to what you are looking for but the API is different.

Please check and tell me what you think.

**Comment by ayushin** [comment]
well, i've played with https://pub.dev/packages/flutter_bloc_patterns but that did not really produce the results i wanted, so i have given it a go myself:

https://pub.dev/packages/list_bloc

If anybody likes to comment or contribute - greatly appreciated!
