### ISSUE TITLE
SelectFieldBloc

### ISSUE THREAD

**Issue by angwandi** [GiancarloCode/form_bloc#81]
Is there a way to add widgets to the item list instead of just a simple String? 
Something like below?
// ignore: close_sinks
  final  category= SelectFieldBloc(
    items: [
      Row(
        children: <Widget>[Icon(Icons.category), Text("Type 01")],
      ),
    ],
  );

**Comment by GiancarloCode** [comment]
Hello,
SelectFieldBloc use Generic Types
```dart
SelectFieldBloc<Value, ExtraData>
```
So you can set the type of item in `Value`
```dart
final categories = SelectFieldBloc<Category, Object>();
```
___
I also see that you are trying to add widgets as type, in general **that is wrong.**

The type should be a `model` (Category, Country, User, etc.) and not related to the UI, in this way you can have your business logic and validation isolated from the UI, and easily exchange widgets.

Actually the `SelectFieldBloc` is compatible this built-in widgets:
* `DropdownFieldBlocBuilder`
* `RadioButtonGroupFieldBlocBuilder`

But you can easily use any widgets.

Here are some examples:
* Dropdown with search: https://github.com/GiancarloCode/form_bloc/issues/64#issuecomment-613836269
* Image field: https://github.com/GiancarloCode/form_bloc/issues/57#issuecomment-609565908

**Comment by angwandi** [comment]
Alright, thank you once again

**Comment by angwandi** [comment]
Hey,

please check this gist for me and instruct me on how to use the formbloc
efficiently. I feel like most  of the work is being done on the main
thread.
data from this form will be saved on Firebase.

https://gist.github.com/angwandi/8cdf903da553f68f83c3ee5acd16e623

*Sent from my hp omen Win 10*



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
06/05/20,
01:58:00

**Comment by GiancarloCode** [comment]
Hello
It looks good, and doesn't seem to have any performance issues, so there's no problem.

Have you seen performance issues? Remember to run & test it in **release or profile** mode to be sure.

Recommendations:

* Create `analysis_options.yaml` https://github.com/GiancarloCode/form_bloc/issues/7, with this you don't need to use `// ignore: close_sinks`
  * Maybe use this plugins in this file https://pub.dev/packages/pedantic or https://pub.dev/packages/dart_style
* Close all conditional fields.
* In your date pickers if use `DateTime.now()` set `firstDate` before `initialDate`.

___
Overall okay, good job :)

**Comment by angwandi** [comment]
Thank you.

I have this message: I/Choreographer(16053): Skipped 75 frames!  The
application may be doing too much work on its main thread.

And also trying to use select_dialog: ^1.0.7 with form bloc and getting
this error : And because no versions of flutter_form_bloc match >0.14.0
<0.15.0, select_dialog >=1.0.7 is incompatible with flutter_form_bloc
^0.14.0.

Any help on that one?

Regards,

*Sent from my hp omen Win 10*



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
06/05/20,
18:14:43
