### ISSUE TITLE
Document Upload

### ISSUE THREAD

**Issue by TafadzwaD** [GiancarloCode/form_bloc#83]
Is there a way of doing a document upload using this package. I am using the form Wizard and in one of the steps i need to perform a document upload. How best can i do that?

@GiancarloCode Thanks for this wonderful package

**Comment by GiancarloCode** [comment]
Hi thanks :)
Check this example:
https://github.com/GiancarloCode/form_bloc/issues/57#issuecomment-609565908

That example is for pick image but it is basically the same, just replace the Image picker plugin to any file picker plugin you want.

It can be this https://pub.dev/packages/file_picker, although I have not thoroughly tested it :D

**Comment by GiancarloCode** [comment]
@TafadzwaD 

Hello, check this :)

```yaml
dependencies:
    file_picker: ^1.9.0+1
```

```dart
class FileFieldBlocBuilder extends StatelessWidget {
  const FileFieldBlocBuilder({
    Key key,
    @required this.fileFieldBloc,
  }) : super(key: key);

  final InputFieldBloc<File, Object> fileFieldBloc;

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<InputFieldBloc<File, Object>,
        InputFieldBlocState<File, Object>>(
      bloc: fileFieldBloc,
      builder: (context, state) {
        return GestureDetector(
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: InputDecorator(
              decoration: InputDecoration(
                labelText: 'Select a File',
                errorText: state.canShowError
                    ? FieldBlocBuilder.defaultErrorBuilder(
                        context,
                        state.error,
                        fileFieldBloc,
                      )
                    : null,
                suffixIcon: AnimatedOpacity(
                  duration: Duration(milliseconds: 400),
                  opacity: state.value == null ? 0.0 : 1.0,
                  child: InkWell(
                    borderRadius: BorderRadius.circular(25),
                    child: Icon(Icons.clear),
                    onTap: state.value == null ? null : fileFieldBloc.clear,
                  ),
                ),
              ),
              child: Text(state?.value?.path?.split('/')?.last ?? ''),
            ),
          ),
          onTap: () async {
            final file = await FilePicker.getFile();
            if (file != null) {
              fileFieldBloc.updateValue(file);
            }
          },
        );
      },
    );
  }
}
```

```dart
...
build...
FileFieldBlocBuilder(fileFieldBloc: formBloc.file),
...
```

**Comment by TafadzwaD** [comment]
Thanks for the prompt response @GiancarloCode .

I am having difficulties implementing the solution in a stepper Widget setup. My case is that the File upload widget is coming after other steps and resulting in an error after moving to the file upload widget. Saying it has been called on null

**Comment by TafadzwaD** [comment]
I would prefer the file upload to be part of the stepper timeline rather than redirecting to a new screen.

**Comment by TafadzwaD** [comment]
Something like

`return FormBlocStep ( File Upload Code Here)`

**Comment by GiancarloCode** [comment]
You could do it but you must create or search for a widget that allows you to create your own file picker Widget, in this way you can integrate it into a `FormBlockStep` instad on new screen to select the file.

That is outside the scope of this library, but if you create it or find it this widget , I will help you integrate it.

**Comment by TafadzwaD** [comment]
Noted @GiancarloCode . Thank you very much
