### ISSUE TITLE
Unable to modify the CONTINUE or CANCEL buttons in Wizard

### ISSUE THREAD

**Issue by CarltonBranch** [GiancarloCode/form_bloc#84]
Great library! Works like a dream.
One thing: Is there a way to modify the CONTINUE or CANCEL buttons.
I'd like to style the CONTINUE button differently than default and hide the CANCEL button.

Thanks again.

**Comment by GiancarloCode** [comment]
Hi, thanks
Checkout `controlsBuilder`
https://pub.dev/documentation/flutter_form_bloc/latest/flutter_form_bloc/StepperFormBlocBuilder/controlsBuilder.html

**Comment by CarltonBranch** [comment]
Thanks so much.
