### ISSUE TITLE
ConditionalFields in a List or group fields

### ISSUE THREAD

**Issue by angwandi** [GiancarloCode/form_bloc#85]
Is there a way to use conditional fields in a List?
this :
![condition](https://user-images.githubusercontent.com/31923567/81500579-bd524500-92db-11ea-81cc-d2905f3c4e65.png)

in this : 
![list](https://user-images.githubusercontent.com/31923567/81500592-d0651500-92db-11ea-9fc4-34d1aa3f110a.png)

Thank you.

**Comment by GiancarloCode** [comment]
Hello, I created the `CanShowFieldBlocBuilder` widget, which will take care of showing and hiding the child if the field is in the form, is the widget that all built-in widgets use.

You can wrap the item widget of your list with this widget like this

```dart
   CanShowFieldBlocBuilder(
      fieldBloc: fieldBloc,
      builder: (context, canShow) {
        return Card(
            //,,,
            );
      },
    );
```

<details><summary>Full code</summary>
<p>

```dart

class MemberCard extends StatelessWidget {
  final int memberIndex;
  final MemberFieldBloc memberField;

  final VoidCallback onRemoveMember;
  final VoidCallback onAddHobby;

  const MemberCard({
    Key key,
    @required this.memberIndex,
    @required this.memberField,
    @required this.onRemoveMember,
    @required this.onAddHobby,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CanShowFieldBlocBuilder(
      fieldBloc: memberField,
      builder: (context, canShow) {
        return Card(
          color: Colors.blue[100],
          margin: const EdgeInsets.all(8.0),
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: Column(
              children: <Widget>[
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: <Widget>[
                    Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Text(
                        'Member #${memberIndex + 1}',
                        style: TextStyle(fontSize: 20),
                      ),
                    ),
                    IconButton(
                      icon: Icon(Icons.delete),
                      onPressed: onRemoveMember,
                    ),
                  ],
                ),
                TextFieldBlocBuilder(
                  textFieldBloc: memberField.firstName,
                  decoration: InputDecoration(
                    labelText: 'First Name',
                  ),
                ),
                TextFieldBlocBuilder(
                  textFieldBloc: memberField.lastName,
                  decoration: InputDecoration(
                    labelText: 'Last Name',
                  ),
                ),
                BlocBuilder<ListFieldBloc<TextFieldBloc>,
                    ListFieldBlocState<TextFieldBloc>>(
                  bloc: memberField.hobbies,
                  builder: (context, state) {
                    if (state.fieldBlocs.isNotEmpty) {
                      return ListView.builder(
                        shrinkWrap: true,
                        physics: NeverScrollableScrollPhysics(),
                        itemCount: state.fieldBlocs.length,
                        itemBuilder: (context, i) {
                          final hobbyFieldBloc = state.fieldBlocs[i];
                          return Card(
                            color: Colors.blue[50],
                            child: Row(
                              children: <Widget>[
                                Expanded(
                                  child: TextFieldBlocBuilder(
                                    textFieldBloc: hobbyFieldBloc,
                                    decoration: InputDecoration(
                                      labelText: 'Hobby #${i + 1}',
                                    ),
                                  ),
                                ),
                                IconButton(
                                  icon: Icon(Icons.delete),
                                  onPressed: () =>
                                      memberField.hobbies.removeFieldBlocAt(i),
                                ),
                              ],
                            ),
                          );
                        },
                      );
                    }
                    return Container();
                  },
                ),
                FlatButton(
                  color: Colors.white,
                  onPressed: onAddHobby,
                  child: Text('ADD HOBBY'),
                ),
              ],
            ),
          ),
        );
      },
    );
  }
}
```

</p>
</details>

Or you can even do it with the list directly,
```dart
return CanShowFieldBlocBuilder(
   fieldBloc: formBloc.members,
   builder: (context, canShow) {
     return ListView.builder(
       shrinkWrap: true,
       physics: const NeverScrollableScrollPhysics(),
       itemCount: state.fieldBlocs.length,
       itemBuilder: (context, i) {
         return MemberCard(
           memberIndex: i,
           memberField: state.fieldBlocs[i],
           onRemoveMember: () =>
               formBloc.removeMember(i),
           onAddHobby: () =>
               formBloc.addHobbyToMember(i),
         );
       },
     );
   },
 );
```

**Comment by angwandi** [comment]
Oh Nice! How do we go out to use the canShow ?

**Comment by GiancarloCode** [comment]
You don't actually have to do anything, `canShow` only notifies you if you should show the widget, but you only uses it if you want to create some different animation.

**Comment by angwandi** [comment]
Okay, I just want to hide and show a Texfieldbloc or a widget with conditions in a list widget. I try to go through it

**Comment by angwandi** [comment]
Can you please assist with an example of how to do it. Hide and show a widget within a list based on condition  using the code above. And also show of a bit of animation. Will be much appreciated

**Comment by GiancarloCode** [comment]
@angwandi Just wrap the widget with `canShowFieldBlocBuilder`, that will do the magic :)

**Comment by GiancarloCode** [comment]
@angwandi  I hope you do it, but if you do not, please make a small app and I will guide you :)

**Comment by mijinitech** [comment]
![ticket 1](https://user-images.githubusercontent.com/60987979/81808829-fdf2ce00-9528-11ea-84ec-697e3703e3a7.png)

from the above, when you select free , price fieldbloc should be removed

![ticket](https://user-images.githubusercontent.com/60987979/81808839-00edbe80-9529-11ea-8427-aecd06dbe7ac.png)

code : https://gist.github.com/angwandi/60b01b8fb987c92f2d8a2ea425e52154
and 
here for the card to be populated in the list : https://gist.github.com/angwandi/1dd854d5d20ef4078b342a64f4e6a8e9

Thanks for your time

**Comment by angwandi** [comment]
![add](https://user-images.githubusercontent.com/31923567/81809542-4068da80-952a-11ea-938a-f1f2dcea34ba.png)
This is the addTicket function

**Comment by GiancarloCode** [comment]
Hello, I see, I did not understand you, sorry.

At the moment it is impossible to have conditional fields in a `GroupFieldBloc`, in the future I will change it or add a` MapFieldBloc`.

Sorry :(

At the moment, as a temporary solution you could try to transform your ticketField (GroupFieldBloc) into a `ListField`, this way you can remove fields from that list.

Later I see if I can give you an example.

**Comment by angwandi** [comment]
Alright, I will really appreciate it

**Comment by mijinitech** [comment]
> Hello, I see, I did not understand you, sorry.
> 
> At the moment it is impossible to have conditional fields in a `GroupFieldBloc`, in the future I will change it or add a` MapFieldBloc`.
> 
> Sorry :(
> 
> At the moment, as a temporary solution you could try to transform your ticketField (GroupFieldBloc) into a `ListField`, this way you can remove fields from that list.
> 
> Later I see if I can give you an example.

Hey, Hope you're well,

Still waiting to see the example

**Comment by GiancarloCode** [comment]
@angwandi 
Hello, I apologize, unfortunately I did not have much free time :*(

I just checked well, but unfortunately it is not possible, you will have to wait for me to do a reimplementation of the GroupFieldBloc, or add a MapFieldBloc.

I will plan it for next week, since I want to migrate the core to make it more flexible.

sorry again :)

**Comment by angwandi** [comment]
No worries, that's cool. I will wait till next week. I am working on my final year uni project, so no pressure. Thanks for your reply anyway.

**Comment by angwandi** [comment]
Because select_dialog >=1.0.7 depends on rxdart ^0.23.1 and flutter_form_bloc 0.14.0 depends on rxdart ^0.24.0, select_dialog >=1.0.7 is incompatible with flutter_form_bloc 0.14.0.

And also, this error?

**Comment by GiancarloCode** [comment]
@angwandi 
`select_dialog` should be updated to `rxdart ^0.24.0`.

You can comment the issue so that they give priority
https://github.com/davidsdearaujo/select_dialog/issues/14

And if you are eager, you can make a fork and update the version and use your fork while, and maybe do the pull request ;)

**Comment by angwandi** [comment]
Done, thanks

**Comment by victorcatn** [comment]
I am facing the same issue, so I will create a ListFieldBloc<SingleFieldBloc>, Hopefully you can get time to fix the GroupFieldBloc or maybe somebody with the abilities can make a PR with the fix.

**Comment by sheriffyusuf** [comment]
Hello, Please am having issues with this. I can't used conditional fields with groupfieldbloc.

**Comment by mghase** [comment]
Any update
