### ISSUE TITLE
Conflict with Hydrated Bloc

### ISSUE THREAD

**Issue by deceive3w** [GiancarloCode/form_bloc#86]
Unhandled Exception: Unhandled error Unhandled error type 'FormBlocDelegate' is not a subtype of type 'HydratedBlocDelegate'

**Comment by felangel** [comment]
This should be solved by upgrading the package to bloc v5.0.0 👍

**Comment by GiancarloCode** [comment]
Thank you @felangel, it was solved in `flutter_form_bloc: ^0.15.0`.
