### ISSUE TITLE
How to change input color in the DropdownFieldBlocBuilder?

### ISSUE THREAD

**Issue by data987** [GiancarloCode/form_bloc#87]
I can change the label and the container color but I couldn't change the input from the DropdownFieldBloc

**Comment by GiancarloCode** [comment]
At the moment this label use
```dart
Theme.of(context).textTheme.subhead
```
you can wrap the widget or form in a theme and change it.

```dart
       Theme(
          data: Theme.of(context).copyWith(
            textTheme: Theme.of(context).textTheme.copyWith(
                  subhead: Theme.of(context).textTheme.subhead.copyWith(
                        color: Colors.red,
                      ),
                ),
          ),
          child: DropdownFieldBlocBuilder(
            selectFieldBloc: null,
            itemBuilder: null,
          ),
        ),
```



I will update the styles to flutter 1.17 tomorrow, I think I can include `style` property to assign a style, this applies to the text in the input decorator as the items in the drop down.
Do you have any suggestion?

**Comment by data987** [comment]
Thank you so much for your answer! I'm gonna try this approach.

well, I haven't had any problems so far, If I have any suggestions I'm gonna tell you as soon as possible. 👌
