### ISSUE TITLE
Dropdown or Selectfield

### ISSUE THREAD

**Issue by HathTech** [GiancarloCode/form_bloc#93]
Is it possible to have a structure for the select field like this - {value: 1, title: "abc"}

**Comment by GiancarloCode** [comment]
Hello,
SelectFieldBloc use Generic Types
```dart
SelectFieldBloc<Value, ExtraData>
```
So you can set the type of item in `Value`
```dart
final categories = SelectFieldBloc<MyClass, Object>();
```
I recommend that you create a class so you have static analysis and clean code, but remember to override `hashCode` and `==`, you can do it manually or use equatable, built_value, freezed, etc...

```dart
class MyClass {
  String title;
  int value;

  MyClass({this.value, this.title});

  // TODO: override hashCode and == operator
}
```
or for simple case use `Tuple` type, https://pub.dev/packages/tuple
```dart
SelectFieldBloc<Tuple2<String, int>, ExtraData>
```



___

**Comment by HathTech** [comment]
Awesome

**Comment by HathTech** [comment]
How can I pass some initial value say I want to fetch users based on some id. 
How can I pass id to the bloc?

**Comment by GiancarloCode** [comment]
@HathTech  this is a demo and tutorial
https://giancarlocode.github.io/form_bloc/#/loading_and_initializing_example

This the full code
https://github.com/GiancarloCode/form_bloc/blob/master/form_bloc_web/lib/examples/loading_and_initializing_form.dart
